import {
  Injectable,
  Logger,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  private readonly logger = new Logger(PrismaService.name);

  async onModuleInit() {
    const attempts = 8;
    let lastError: unknown;
    for (let attempt = 1; attempt <= attempts; attempt += 1) {
      try {
        await this.$connect();
        await this.ensureSqliteCoreTables();
        return;
      } catch (error) {
        lastError = error;
        const message = error instanceof Error ? error.message : 'unknown';
        if (attempt === attempts) {
          break;
        }
        this.logger.warn(
          `数据库连接失败，${attempt}/${attempts}，800ms 后重试：${message}`,
        );
        await new Promise((resolve) => setTimeout(resolve, 800));
      }
    }
    throw lastError;
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }

  private async ensureSqliteCoreTables() {
    const databaseUrl = `${process.env.SQLITE_DATABASE_URL || process.env.DATABASE_URL || ''}`;
    if (!databaseUrl.startsWith('file:')) {
      return;
    }

    const statements = [
      `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY NOT NULL,
        username TEXT NOT NULL,
        email TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        last_login_at DATETIME,
        kaypal_user_id TEXT,
        role TEXT NOT NULL DEFAULT 'operator',
        commercial_execution_allowed BOOLEAN NOT NULL DEFAULT false,
        plan_mode TEXT NOT NULL DEFAULT 'trial',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users(username)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users(email)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS users_kaypal_user_id_key ON users(kaypal_user_id)`,
      `CREATE INDEX IF NOT EXISTS users_status_idx ON users(status)`,
      `CREATE INDEX IF NOT EXISTS users_role_idx ON users(role)`,
      `CREATE TABLE IF NOT EXISTS user_sessions (
        id TEXT PRIMARY KEY NOT NULL,
        user_id TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        expires_at DATETIME NOT NULL,
        last_used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON user_sessions(user_id)`,
      `CREATE INDEX IF NOT EXISTS user_sessions_expires_at_idx ON user_sessions(expires_at)`,
      `CREATE TABLE IF NOT EXISTS system_configs (
        key TEXT PRIMARY KEY NOT NULL,
        value TEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS tenants (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        slug TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        owner_user_id TEXT NOT NULL,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT tenants_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS tenants_slug_key ON tenants(slug)`,
      `CREATE INDEX IF NOT EXISTS tenants_owner_user_id_idx ON tenants(owner_user_id)`,
      `CREATE INDEX IF NOT EXISTS tenants_status_idx ON tenants(status)`,
      `CREATE TABLE IF NOT EXISTS tenant_members (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'admin',
        status TEXT NOT NULL DEFAULT 'active',
        permissions JSONB NOT NULL DEFAULT '[]',
        joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT tenant_members_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT tenant_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS tenant_members_tenant_id_user_id_key ON tenant_members(tenant_id, user_id)`,
      `CREATE INDEX IF NOT EXISTS tenant_members_tenant_id_idx ON tenant_members(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS tenant_members_user_id_idx ON tenant_members(user_id)`,
      `CREATE INDEX IF NOT EXISTS tenant_members_role_idx ON tenant_members(role)`,
      `CREATE INDEX IF NOT EXISTS tenant_members_status_idx ON tenant_members(status)`,
      `CREATE TABLE IF NOT EXISTS tenant_entitlements (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL,
        source TEXT NOT NULL,
        plan TEXT NOT NULL DEFAULT 'FREE',
        status TEXT NOT NULL DEFAULT 'active',
        features JSONB NOT NULL DEFAULT '[]',
        commercial_execution_allowed BOOLEAN NOT NULL DEFAULT false,
        external_subscription_id TEXT,
        period_start DATETIME,
        period_end DATETIME,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT tenant_entitlements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS tenant_entitlements_tenant_id_source_key ON tenant_entitlements(tenant_id, source)`,
      `CREATE INDEX IF NOT EXISTS tenant_entitlements_tenant_id_idx ON tenant_entitlements(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS tenant_entitlements_source_idx ON tenant_entitlements(source)`,
      `CREATE INDEX IF NOT EXISTS tenant_entitlements_plan_idx ON tenant_entitlements(plan)`,
      `CREATE INDEX IF NOT EXISTS tenant_entitlements_status_idx ON tenant_entitlements(status)`,
      `CREATE INDEX IF NOT EXISTS tenant_entitlements_period_end_idx ON tenant_entitlements(period_end)`,
      `CREATE TABLE IF NOT EXISTS schedule_configs (
        id TEXT PRIMARY KEY NOT NULL,
        task_type TEXT NOT NULL,
        cron_expr TEXT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT false,
        config JSONB,
        last_run_time DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS schedule_configs_task_type_key ON schedule_configs(task_type)`,
      `CREATE TABLE IF NOT EXISTS app_install_states (
        id TEXT PRIMARY KEY NOT NULL,
        user_id TEXT NOT NULL,
        tenant_id TEXT,
        actor_user_id TEXT,
        app_key TEXT NOT NULL,
        purchase_status TEXT NOT NULL DEFAULT 'not_purchased',
        install_status TEXT NOT NULL DEFAULT 'not_installed',
        entitlement_snapshot JSONB,
        settings JSONB,
        purchased_at DATETIME,
        installed_at DATETIME,
        uninstalled_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT app_install_states_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS app_install_states_user_id_app_key_key ON app_install_states(user_id, app_key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS app_install_states_tenant_id_app_key_key ON app_install_states(tenant_id, app_key)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_user_id_idx ON app_install_states(user_id)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_tenant_id_idx ON app_install_states(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_actor_user_id_idx ON app_install_states(actor_user_id)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_app_key_idx ON app_install_states(app_key)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_purchase_status_idx ON app_install_states(purchase_status)`,
      `CREATE INDEX IF NOT EXISTS app_install_states_install_status_idx ON app_install_states(install_status)`,
      `CREATE TABLE IF NOT EXISTS wecom_assistant_integrations (
        id TEXT PRIMARY KEY NOT NULL,
        user_id TEXT NOT NULL,
        name TEXT NOT NULL,
        encrypted_webhook_url TEXT NOT NULL,
        masked_webhook_url TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        last_tested_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS wecom_assistant_settings (
        id TEXT PRIMARY KEY NOT NULL,
        integration_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        brand_name TEXT,
        store_name TEXT,
        reply_style TEXT,
        transfer_keywords JSONB NOT NULL DEFAULT '[]',
        send_to_wecom BOOLEAN NOT NULL DEFAULT true,
        auto_send_to_customer BOOLEAN NOT NULL DEFAULT false,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT wecom_assistant_settings_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES wecom_assistant_integrations(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE TABLE IF NOT EXISTS wecom_outbound_messages (
        id TEXT PRIMARY KEY NOT NULL,
        user_id TEXT NOT NULL,
        integration_id TEXT NOT NULL,
        channel TEXT NOT NULL DEFAULT 'wecom',
        message_type TEXT NOT NULL,
        content TEXT NOT NULL,
        status TEXT NOT NULL,
        error_message TEXT,
        sent_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT wecom_outbound_messages_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES wecom_assistant_integrations(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS wecom_assistant_settings_integration_id_key ON wecom_assistant_settings(integration_id)`,
      `CREATE INDEX IF NOT EXISTS wecom_assistant_integrations_user_id_idx ON wecom_assistant_integrations(user_id)`,
      `CREATE INDEX IF NOT EXISTS wecom_assistant_integrations_status_idx ON wecom_assistant_integrations(status)`,
      `CREATE INDEX IF NOT EXISTS wecom_assistant_integrations_updated_at_idx ON wecom_assistant_integrations(updated_at)`,
      `CREATE INDEX IF NOT EXISTS wecom_assistant_settings_user_id_idx ON wecom_assistant_settings(user_id)`,
      `CREATE INDEX IF NOT EXISTS wecom_outbound_messages_user_id_idx ON wecom_outbound_messages(user_id)`,
      `CREATE INDEX IF NOT EXISTS wecom_outbound_messages_integration_id_idx ON wecom_outbound_messages(integration_id)`,
      `CREATE INDEX IF NOT EXISTS wecom_outbound_messages_status_idx ON wecom_outbound_messages(status)`,
      `CREATE INDEX IF NOT EXISTS wecom_outbound_messages_created_at_idx ON wecom_outbound_messages(created_at)`,
      `CREATE TABLE IF NOT EXISTS crm_companies (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        name TEXT NOT NULL,
        domain TEXT,
        industry TEXT,
        phone TEXT,
        website TEXT,
        city TEXT,
        employees INTEGER,
        annual_revenue_cents INTEGER NOT NULL DEFAULT 0,
        owner_user_id TEXT,
        tags JSONB NOT NULL DEFAULT '[]',
        metadata JSONB,
        archived_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_companies_owner_id_idx ON crm_companies(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_companies_tenant_id_idx ON crm_companies(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_companies_name_idx ON crm_companies(name)`,
      `CREATE INDEX IF NOT EXISTS crm_companies_domain_idx ON crm_companies(domain)`,
      `CREATE INDEX IF NOT EXISTS crm_companies_industry_idx ON crm_companies(industry)`,
      `CREATE INDEX IF NOT EXISTS crm_companies_updated_at_idx ON crm_companies(updated_at)`,
      `CREATE TABLE IF NOT EXISTS crm_customers (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        display_name TEXT NOT NULL,
        company_id TEXT,
        title TEXT,
        email TEXT,
        phone TEXT,
        wechat TEXT,
        status TEXT NOT NULL DEFAULT 'new',
        source_platform TEXT,
        source_keyword TEXT,
        matched_keyword TEXT,
        source_url TEXT,
        source_text TEXT,
        latest_reply TEXT,
        score INTEGER NOT NULL DEFAULT 0,
        tags JSONB NOT NULL DEFAULT '[]',
        profile_url TEXT,
        external_user_id TEXT,
        dedupe_key TEXT,
        assigned_user_id TEXT,
        first_interaction_task_id TEXT,
        latest_interaction_task_id TEXT,
        metadata JSONB,
        archived_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS crm_customers_owner_id_dedupe_key_key ON crm_customers(owner_id, dedupe_key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS crm_customers_tenant_id_dedupe_key_key ON crm_customers(tenant_id, dedupe_key)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_owner_id_idx ON crm_customers(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_tenant_id_idx ON crm_customers(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_company_id_idx ON crm_customers(company_id)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_status_idx ON crm_customers(status)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_email_idx ON crm_customers(email)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_phone_idx ON crm_customers(phone)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_source_platform_idx ON crm_customers(source_platform)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_source_keyword_idx ON crm_customers(source_keyword)`,
      `CREATE INDEX IF NOT EXISTS crm_customers_updated_at_idx ON crm_customers(updated_at)`,
      `CREATE TABLE IF NOT EXISTS crm_opportunities (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        name TEXT NOT NULL,
        stage TEXT NOT NULL DEFAULT 'qualified',
        amount_cents INTEGER NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'CNY',
        probability INTEGER NOT NULL DEFAULT 20,
        company_id TEXT,
        primary_customer_id TEXT,
        close_date DATETIME,
        next_step TEXT,
        competitor TEXT,
        source TEXT,
        metadata JSONB,
        archived_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_owner_id_idx ON crm_opportunities(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_tenant_id_idx ON crm_opportunities(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_company_id_idx ON crm_opportunities(company_id)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_primary_customer_id_idx ON crm_opportunities(primary_customer_id)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_stage_idx ON crm_opportunities(stage)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_close_date_idx ON crm_opportunities(close_date)`,
      `CREATE INDEX IF NOT EXISTS crm_opportunities_updated_at_idx ON crm_opportunities(updated_at)`,
      `CREATE TABLE IF NOT EXISTS crm_tasks (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        title TEXT NOT NULL,
        description TEXT,
        status TEXT NOT NULL DEFAULT 'open',
        priority TEXT NOT NULL DEFAULT 'normal',
        due_at DATETIME,
        completed_at DATETIME,
        assignee_id TEXT,
        company_id TEXT,
        customer_id TEXT,
        opportunity_id TEXT,
        metadata JSONB,
        archived_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_owner_id_idx ON crm_tasks(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_tenant_id_idx ON crm_tasks(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_company_id_idx ON crm_tasks(company_id)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_customer_id_idx ON crm_tasks(customer_id)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_opportunity_id_idx ON crm_tasks(opportunity_id)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_status_idx ON crm_tasks(status)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_priority_idx ON crm_tasks(priority)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_due_at_idx ON crm_tasks(due_at)`,
      `CREATE INDEX IF NOT EXISTS crm_tasks_updated_at_idx ON crm_tasks(updated_at)`,
      `CREATE TABLE IF NOT EXISTS crm_notes (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        body TEXT NOT NULL,
        created_by TEXT,
        company_id TEXT,
        customer_id TEXT,
        opportunity_id TEXT,
        metadata JSONB,
        archived_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_notes_owner_id_idx ON crm_notes(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_notes_tenant_id_idx ON crm_notes(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_notes_company_id_idx ON crm_notes(company_id)`,
      `CREATE INDEX IF NOT EXISTS crm_notes_customer_id_idx ON crm_notes(customer_id)`,
      `CREATE INDEX IF NOT EXISTS crm_notes_opportunity_id_idx ON crm_notes(opportunity_id)`,
      `CREATE INDEX IF NOT EXISTS crm_notes_created_at_idx ON crm_notes(created_at)`,
      `CREATE TABLE IF NOT EXISTS crm_timeline_events (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        customer_id TEXT,
        company_id TEXT,
        opportunity_id TEXT,
        task_id TEXT,
        note_id TEXT,
        related_interaction_task_id TEXT,
        related_runtime_execution_id TEXT,
        event_type TEXT NOT NULL,
        channel TEXT,
        content TEXT,
        reply_content TEXT,
        status TEXT,
        failure_reason TEXT,
        evidence JSONB,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_owner_id_idx ON crm_timeline_events(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_tenant_id_idx ON crm_timeline_events(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_customer_id_idx ON crm_timeline_events(customer_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_company_id_idx ON crm_timeline_events(company_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_opportunity_id_idx ON crm_timeline_events(opportunity_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_task_id_idx ON crm_timeline_events(task_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_note_id_idx ON crm_timeline_events(note_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_related_interaction_task_id_idx ON crm_timeline_events(related_interaction_task_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_related_runtime_execution_id_idx ON crm_timeline_events(related_runtime_execution_id)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_event_type_idx ON crm_timeline_events(event_type)`,
      `CREATE INDEX IF NOT EXISTS crm_timeline_events_created_at_idx ON crm_timeline_events(created_at)`,
      `CREATE TABLE IF NOT EXISTS materials (
        id TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        content TEXT,
        summary TEXT,
        source_url TEXT NOT NULL DEFAULT '',
        platform TEXT NOT NULL DEFAULT 'Other',
        author TEXT NOT NULL DEFAULT '',
        publish_date DATETIME,
        collect_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        status TEXT NOT NULL DEFAULT 'unmined',
        mining_count INTEGER NOT NULL DEFAULT 0,
        keywords JSONB NOT NULL DEFAULT '[]',
        metadata JSONB,
        image_url TEXT,
        original_image_url TEXT,
        hasImage BOOLEAN NOT NULL DEFAULT false,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS materials_status_idx ON materials(status)`,
      `CREATE INDEX IF NOT EXISTS materials_collect_date_idx ON materials(collect_date)`,
      `CREATE INDEX IF NOT EXISTS materials_platform_idx ON materials(platform)`,
      `CREATE INDEX IF NOT EXISTS materials_hasImage_idx ON materials(hasImage)`,
      `CREATE TABLE IF NOT EXISTS topics (
        id TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        summary TEXT,
        source_type TEXT NOT NULL DEFAULT '外部采集',
        keywords JSONB NOT NULL DEFAULT '[]',
        ai_score REAL,
        score_details JSONB,
        score_reason TEXT,
        reasoning TEXT,
        search_queries JSONB NOT NULL DEFAULT '[]',
        status TEXT NOT NULL DEFAULT 'pending',
        is_published BOOLEAN NOT NULL DEFAULT false,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS topics_status_idx ON topics(status)`,
      `CREATE INDEX IF NOT EXISTS topics_is_published_idx ON topics(is_published)`,
      `CREATE INDEX IF NOT EXISTS topics_created_at_idx ON topics(created_at)`,
      `CREATE TABLE IF NOT EXISTS styles (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        description TEXT,
        prompt_template TEXT NOT NULL DEFAULT '',
        parameters JSONB,
        is_default BOOLEAN NOT NULL DEFAULT false,
        type TEXT NOT NULL DEFAULT 'article',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS styles_name_key ON styles(name)`,
      `CREATE INDEX IF NOT EXISTS styles_type_idx ON styles(type)`,
      `CREATE TABLE IF NOT EXISTS ai_platforms (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        base_url TEXT NOT NULL DEFAULT '',
        api_key TEXT NOT NULL DEFAULT '',
        enabled BOOLEAN NOT NULL DEFAULT true,
        config JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS ai_platforms_name_key ON ai_platforms(name)`,
      `CREATE TABLE IF NOT EXISTS ai_models (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        model_id TEXT NOT NULL,
        platform_id TEXT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT true,
        config JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT ai_models_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES ai_platforms(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS ai_models_platform_id_model_id_key ON ai_models(platform_id, model_id)`,
      `CREATE TABLE IF NOT EXISTS default_model_configs (
        id TEXT PRIMARY KEY NOT NULL,
        purpose TEXT NOT NULL,
        model_id TEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS default_model_configs_purpose_key ON default_model_configs(purpose)`,
      `CREATE TABLE IF NOT EXISTS articles (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        topic_id TEXT,
        title TEXT NOT NULL,
        content TEXT NOT NULL DEFAULT '',
        content_type TEXT NOT NULL DEFAULT 'article',
        content_format TEXT NOT NULL DEFAULT 'markdown',
        workspace_brief JSONB,
        workspace_outline JSONB,
        workspace_step TEXT NOT NULL DEFAULT 'brief',
        workspace_revision INTEGER NOT NULL DEFAULT 1,
        xiaohongshu_data JSONB,
        raw_html TEXT,
        final_html TEXT,
        template_id TEXT,
        style_id TEXT,
        model_id TEXT,
        status TEXT NOT NULL DEFAULT 'draft',
        cover_image TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT articles_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT articles_style_id_fkey FOREIGN KEY (style_id) REFERENCES styles(id) ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT articles_model_id_fkey FOREIGN KEY (model_id) REFERENCES ai_models(id) ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE INDEX IF NOT EXISTS articles_status_idx ON articles(status)`,
      `CREATE INDEX IF NOT EXISTS articles_topic_id_idx ON articles(topic_id)`,
      `CREATE INDEX IF NOT EXISTS articles_content_type_idx ON articles(content_type)`,
      `CREATE INDEX IF NOT EXISTS articles_template_id_idx ON articles(template_id)`,
      `CREATE INDEX IF NOT EXISTS articles_tenant_id_user_id_created_at_idx ON articles(tenant_id, user_id, created_at)`,
      `CREATE TABLE IF NOT EXISTS topic_materials (
        topic_id TEXT NOT NULL,
        material_id TEXT NOT NULL,
        PRIMARY KEY (topic_id, material_id),
        CONSTRAINT topic_materials_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT topic_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE TABLE IF NOT EXISTS sources (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        type TEXT NOT NULL,
        url TEXT NOT NULL,
        config JSONB,
        enabled BOOLEAN NOT NULL DEFAULT true,
        last_crawl_time DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS sources_enabled_idx ON sources(enabled)`,
      `CREATE TABLE IF NOT EXISTS system_logs (
        id TEXT PRIMARY KEY NOT NULL,
        level TEXT NOT NULL DEFAULT 'info',
        content TEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS system_logs_created_at_idx ON system_logs(created_at)`,
      `CREATE INDEX IF NOT EXISTS system_logs_level_idx ON system_logs(level)`,
      `CREATE TABLE IF NOT EXISTS publish_accounts (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        platform TEXT NOT NULL,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'ready',
        app_id TEXT,
        api_token TEXT,
        config JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS publish_accounts_tenant_id_user_id_created_at_idx ON publish_accounts(tenant_id, user_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS publish_accounts_tenant_id_user_id_platform_status_idx ON publish_accounts(tenant_id, user_id, platform, status)`,
      `CREATE TABLE IF NOT EXISTS publish_records (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        durable_record_id TEXT,
        article_id TEXT NOT NULL,
        account_id TEXT NOT NULL,
        platform TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        publish_url TEXT,
        error_message TEXT,
        source_identity JSONB,
        body_snapshot TEXT,
        payload_json JSONB,
        result_json JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT publish_records_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT publish_records_account_id_fkey FOREIGN KEY (account_id) REFERENCES publish_accounts(id) ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE INDEX IF NOT EXISTS publish_records_article_id_idx ON publish_records(article_id)`,
      `CREATE INDEX IF NOT EXISTS publish_records_account_id_idx ON publish_records(account_id)`,
      `CREATE INDEX IF NOT EXISTS publish_records_status_idx ON publish_records(status)`,
      `CREATE INDEX IF NOT EXISTS publish_records_tenant_id_user_id_created_at_idx ON publish_records(tenant_id, user_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS publish_records_tenant_id_user_id_durable_record_id_idx ON publish_records(tenant_id, user_id, durable_record_id)`,
      `CREATE TABLE IF NOT EXISTS interaction_tasks (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        taskType TEXT NOT NULL,
        accountId TEXT,
        sessionId TEXT,
        ruleId TEXT,
        sendMode TEXT NOT NULL DEFAULT 'approval-send',
        status TEXT NOT NULL DEFAULT 'QUEUED',
        riskLevel TEXT NOT NULL DEFAULT 'medium',
        stage TEXT,
        currentTarget TEXT,
        draftText TEXT,
        processedCount INTEGER NOT NULL DEFAULT 0,
        failedCount INTEGER NOT NULL DEFAULT 0,
        skippedCount INTEGER NOT NULL DEFAULT 0,
        batchTargets JSONB,
        batchSummary JSONB,
        events JSONB NOT NULL DEFAULT '[]',
        evidence JSONB NOT NULL DEFAULT '[]',
        config JSONB,
        createdBy TEXT,
        localTaskId TEXT,
        requiresDoubleConfirmation BOOLEAN NOT NULL DEFAULT false,
        createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_status_idx ON interaction_tasks(status)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_taskType_idx ON interaction_tasks(taskType)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_tenant_id_user_id_status_idx ON interaction_tasks(tenant_id, user_id, status)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_tenant_id_user_id_taskType_idx ON interaction_tasks(tenant_id, user_id, taskType)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_tenant_id_user_id_createdAt_idx ON interaction_tasks(tenant_id, user_id, createdAt)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_accountId_idx ON interaction_tasks(accountId)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_sessionId_idx ON interaction_tasks(sessionId)`,
      `CREATE INDEX IF NOT EXISTS interaction_tasks_createdAt_idx ON interaction_tasks(createdAt)`,
      `CREATE TABLE IF NOT EXISTS interaction_task_events (
        id TEXT PRIMARY KEY NOT NULL,
        taskId TEXT NOT NULL,
        stage TEXT NOT NULL,
        level TEXT NOT NULL DEFAULT 'info',
        message TEXT NOT NULL,
        payload JSONB,
        createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS interaction_task_events_taskId_idx ON interaction_task_events(taskId)`,
      `CREATE INDEX IF NOT EXISTS interaction_task_events_createdAt_idx ON interaction_task_events(createdAt)`,
      `CREATE TABLE IF NOT EXISTS local_engine_reply_rules (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        bot_key TEXT NOT NULL DEFAULT 'default',
        config_version INTEGER NOT NULL DEFAULT 1,
        revision INTEGER NOT NULL DEFAULT 1,
        name TEXT,
        industry TEXT,
        tone TEXT,
        send_mode TEXT,
        keywords JSONB NOT NULL DEFAULT '[]',
        forbidden_words JSONB NOT NULL DEFAULT '[]',
        highlights JSONB NOT NULL DEFAULT '[]',
        closing_text TEXT,
        rule_json JSONB NOT NULL DEFAULT '{}',
        escalation_rules JSONB,
        enabled BOOLEAN NOT NULL DEFAULT true,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS local_engine_reply_rules_tenant_id_user_id_bot_key_key ON local_engine_reply_rules(tenant_id, user_id, bot_key)`,
      `CREATE INDEX IF NOT EXISTS local_engine_reply_rules_tenant_id_user_id_updated_at_idx ON local_engine_reply_rules(tenant_id, user_id, updated_at)`,
      `CREATE TABLE IF NOT EXISTS local_engine_agent_sessions (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        source TEXT NOT NULL DEFAULT 'web',
        status TEXT NOT NULL DEFAULT 'draft',
        title TEXT NOT NULL DEFAULT '',
        scope TEXT,
        target_app TEXT,
        instruction TEXT,
        risk_level TEXT,
        events JSONB DEFAULT '[]',
        confirmations JSONB DEFAULT '[]',
        evidence JSONB DEFAULT '[]',
        session_json JSONB NOT NULL DEFAULT '{}',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        completed_at DATETIME
      )`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_source_idx ON local_engine_agent_sessions(source)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_status_idx ON local_engine_agent_sessions(status)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_tenant_id_user_id_source_idx ON local_engine_agent_sessions(tenant_id, user_id, source)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_tenant_id_user_id_status_idx ON local_engine_agent_sessions(tenant_id, user_id, status)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_tenant_id_user_id_updated_at_idx ON local_engine_agent_sessions(tenant_id, user_id, updated_at)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_sessions_updated_at_idx ON local_engine_agent_sessions(updated_at)`,
      `CREATE TABLE IF NOT EXISTS local_engine_agent_confirmations (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        session_id TEXT NOT NULL,
        action TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'pending',
        risk_level TEXT NOT NULL DEFAULT 'low',
        target TEXT,
        target_label TEXT,
        content TEXT,
        reply_text TEXT,
        operator TEXT,
        note TEXT,
        confirmation_json JSONB NOT NULL DEFAULT '{}',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        decided_at DATETIME
      )`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_confirmations_session_id_idx ON local_engine_agent_confirmations(session_id)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_confirmations_status_idx ON local_engine_agent_confirmations(status)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_confirmations_tenant_id_user_id_session_id_idx ON local_engine_agent_confirmations(tenant_id, user_id, session_id)`,
      `CREATE INDEX IF NOT EXISTS local_engine_agent_confirmations_tenant_id_user_id_status_idx ON local_engine_agent_confirmations(tenant_id, user_id, status)`,
      `CREATE TABLE IF NOT EXISTS geo_bridge_tasks (
        id TEXT PRIMARY KEY NOT NULL,
        action_id TEXT NOT NULL,
        action_type TEXT NOT NULL,
        action_title TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'sent_to_ai_content',
        source TEXT NOT NULL DEFAULT 'kaypal-geo',
        brand_id TEXT,
        brand_name TEXT,
        platform TEXT,
        brief TEXT,
        goal TEXT,
        reason TEXT,
        retest_window TEXT,
        return_url TEXT,
        callback_url TEXT,
        keyword TEXT,
        content_preview TEXT,
        result_url TEXT,
        published_url TEXT,
        last_callback_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS geo_bridge_tasks_action_id_key ON geo_bridge_tasks(action_id)`,
      `CREATE INDEX IF NOT EXISTS geo_bridge_tasks_status_idx ON geo_bridge_tasks(status)`,
      `CREATE INDEX IF NOT EXISTS geo_bridge_tasks_platform_idx ON geo_bridge_tasks(platform)`,
      `CREATE INDEX IF NOT EXISTS geo_bridge_tasks_brand_name_idx ON geo_bridge_tasks(brand_name)`,
      `CREATE INDEX IF NOT EXISTS geo_bridge_tasks_updated_at_idx ON geo_bridge_tasks(updated_at)`,
      `CREATE TABLE IF NOT EXISTS redfox_connections (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        name TEXT NOT NULL DEFAULT 'RedFox',
        api_key_encrypted TEXT NOT NULL,
        api_key_masked TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        daily_call_limit INTEGER,
        daily_cost_limit INTEGER,
        last_test_at DATETIME,
        last_error TEXT,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_connections_tenant_id_user_id_key ON redfox_connections(tenant_id, user_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_connections_user_id_idx ON redfox_connections(user_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_connections_tenant_id_idx ON redfox_connections(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_connections_status_idx ON redfox_connections(status)`,
      `CREATE TABLE IF NOT EXISTS redfox_skills (
        id TEXT PRIMARY KEY NOT NULL,
        skill_no TEXT,
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        platform TEXT,
        category TEXT,
        tags JSONB NOT NULL DEFAULT '[]',
        summary TEXT,
        description TEXT,
        input_schema JSONB,
        output_schema JSONB,
        status TEXT NOT NULL DEFAULT 'active',
        raw JSONB,
        synced_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_skills_skill_no_key ON redfox_skills(skill_no)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_skills_code_key ON redfox_skills(code)`,
      `CREATE INDEX IF NOT EXISTS redfox_skills_platform_idx ON redfox_skills(platform)`,
      `CREATE INDEX IF NOT EXISTS redfox_skills_category_idx ON redfox_skills(category)`,
      `CREATE INDEX IF NOT EXISTS redfox_skills_status_idx ON redfox_skills(status)`,
      `CREATE INDEX IF NOT EXISTS redfox_skills_synced_at_idx ON redfox_skills(synced_at)`,
      `CREATE TABLE IF NOT EXISTS redfox_skill_installs (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        skill_id TEXT NOT NULL,
        enabled BOOLEAN NOT NULL DEFAULT true,
        scenario TEXT NOT NULL DEFAULT 'general',
        config JSONB,
        usage_policy JSONB,
        last_used_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_skill_installs_tenant_id_skill_id_scenario_key ON redfox_skill_installs(tenant_id, skill_id, scenario)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_skill_installs_user_id_skill_id_scenario_key ON redfox_skill_installs(user_id, skill_id, scenario)`,
      `CREATE INDEX IF NOT EXISTS redfox_skill_installs_tenant_id_enabled_idx ON redfox_skill_installs(tenant_id, enabled)`,
      `CREATE INDEX IF NOT EXISTS redfox_skill_installs_user_id_enabled_idx ON redfox_skill_installs(user_id, enabled)`,
      `CREATE INDEX IF NOT EXISTS redfox_skill_installs_skill_id_idx ON redfox_skill_installs(skill_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_skill_installs_scenario_idx ON redfox_skill_installs(scenario)`,
      `CREATE TABLE IF NOT EXISTS redfox_interfaces (
        id TEXT PRIMARY KEY NOT NULL,
        platform_code TEXT NOT NULL,
        platform_name TEXT,
        interface_no TEXT,
        code TEXT NOT NULL,
        name TEXT NOT NULL,
        path TEXT NOT NULL,
        method TEXT NOT NULL DEFAULT 'POST',
        scenario TEXT,
        status TEXT NOT NULL DEFAULT 'online',
        category TEXT,
        description TEXT,
        price REAL,
        min_price REAL,
        require_auth BOOLEAN NOT NULL DEFAULT true,
        parameters JSONB,
        examples JSONB,
        raw JSONB,
        synced_at DATETIME NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_interfaces_interface_no_key ON redfox_interfaces(interface_no)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_interfaces_code_key ON redfox_interfaces(code)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS redfox_interfaces_platform_code_path_method_key ON redfox_interfaces(platform_code, path, method)`,
      `CREATE INDEX IF NOT EXISTS redfox_interfaces_platform_code_idx ON redfox_interfaces(platform_code)`,
      `CREATE INDEX IF NOT EXISTS redfox_interfaces_path_idx ON redfox_interfaces(path)`,
      `CREATE INDEX IF NOT EXISTS redfox_interfaces_scenario_idx ON redfox_interfaces(scenario)`,
      `CREATE INDEX IF NOT EXISTS redfox_interfaces_status_idx ON redfox_interfaces(status)`,
      `CREATE INDEX IF NOT EXISTS redfox_interfaces_synced_at_idx ON redfox_interfaces(synced_at)`,
      `CREATE TABLE IF NOT EXISTS redfox_call_logs (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        connection_id TEXT,
        skill_id TEXT,
        skill_code TEXT,
        endpoint TEXT NOT NULL,
        method TEXT NOT NULL DEFAULT 'POST',
        status TEXT NOT NULL DEFAULT 'pending',
        http_status INTEGER,
        cost_points INTEGER NOT NULL DEFAULT 0,
        latency_ms INTEGER,
        retry_count INTEGER NOT NULL DEFAULT 0,
        request_hash TEXT,
        request_summary JSONB,
        response_summary JSONB,
        error_code TEXT,
        error_message TEXT,
        started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ended_at DATETIME,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_tenant_id_started_at_idx ON redfox_call_logs(tenant_id, started_at)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_user_id_started_at_idx ON redfox_call_logs(user_id, started_at)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_connection_id_idx ON redfox_call_logs(connection_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_skill_id_idx ON redfox_call_logs(skill_id)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_skill_code_idx ON redfox_call_logs(skill_code)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_endpoint_idx ON redfox_call_logs(endpoint)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_status_idx ON redfox_call_logs(status)`,
      `CREATE INDEX IF NOT EXISTS redfox_call_logs_request_hash_idx ON redfox_call_logs(request_hash)`,
      `CREATE TABLE IF NOT EXISTS intelligence_items (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        source_id TEXT,
        redfox_skill_id TEXT,
        redfox_call_log_id TEXT,
        material_id TEXT,
        topic_id TEXT,
        growth_lead_id TEXT,
        platform TEXT NOT NULL,
        type TEXT NOT NULL,
        title TEXT NOT NULL,
        content TEXT,
        summary TEXT,
        source_url TEXT,
        source_external_id TEXT,
        author TEXT,
        author_url TEXT,
        publish_date DATETIME,
        metrics JSONB NOT NULL DEFAULT '{}',
        keywords JSONB NOT NULL DEFAULT '[]',
        raw JSONB,
        status TEXT NOT NULL DEFAULT 'new',
        dedupe_key TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS intelligence_items_tenant_id_dedupe_key_key ON intelligence_items(tenant_id, dedupe_key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS intelligence_items_user_id_dedupe_key_key ON intelligence_items(user_id, dedupe_key)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_tenant_id_type_idx ON intelligence_items(tenant_id, type)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_user_id_type_idx ON intelligence_items(user_id, type)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_platform_idx ON intelligence_items(platform)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_status_idx ON intelligence_items(status)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_source_id_idx ON intelligence_items(source_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_redfox_skill_id_idx ON intelligence_items(redfox_skill_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_redfox_call_log_id_idx ON intelligence_items(redfox_call_log_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_material_id_idx ON intelligence_items(material_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_topic_id_idx ON intelligence_items(topic_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_growth_lead_id_idx ON intelligence_items(growth_lead_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_items_created_at_idx ON intelligence_items(created_at)`,
      `CREATE TABLE IF NOT EXISTS benchmark_accounts (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        intelligence_item_id TEXT,
        growth_lead_id TEXT,
        platform TEXT NOT NULL,
        nickname TEXT NOT NULL,
        external_user_id TEXT,
        profile_url TEXT,
        avatar_url TEXT,
        metrics JSONB NOT NULL DEFAULT '{}',
        reason TEXT,
        diagnosis JSONB,
        status TEXT NOT NULL DEFAULT 'watching',
        raw JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS benchmark_accounts_tenant_id_platform_external_user_id_key ON benchmark_accounts(tenant_id, platform, external_user_id)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS benchmark_accounts_user_id_platform_external_user_id_key ON benchmark_accounts(user_id, platform, external_user_id)`,
      `CREATE INDEX IF NOT EXISTS benchmark_accounts_tenant_id_status_idx ON benchmark_accounts(tenant_id, status)`,
      `CREATE INDEX IF NOT EXISTS benchmark_accounts_user_id_status_idx ON benchmark_accounts(user_id, status)`,
      `CREATE INDEX IF NOT EXISTS benchmark_accounts_platform_idx ON benchmark_accounts(platform)`,
      `CREATE INDEX IF NOT EXISTS benchmark_accounts_intelligence_item_id_idx ON benchmark_accounts(intelligence_item_id)`,
      `CREATE INDEX IF NOT EXISTS benchmark_accounts_growth_lead_id_idx ON benchmark_accounts(growth_lead_id)`,
      `CREATE TABLE IF NOT EXISTS intelligence_monitors (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        skill_install_id TEXT,
        type TEXT NOT NULL,
        platform TEXT,
        keyword TEXT,
        account_external_id TEXT,
        industry TEXT,
        schedule TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        config JSONB,
        cost_limit_points INTEGER,
        last_run_at DATETIME,
        next_run_at DATETIME,
        last_error TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_tenant_id_status_idx ON intelligence_monitors(tenant_id, status)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_user_id_status_idx ON intelligence_monitors(user_id, status)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_skill_install_id_idx ON intelligence_monitors(skill_install_id)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_type_idx ON intelligence_monitors(type)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_platform_idx ON intelligence_monitors(platform)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_keyword_idx ON intelligence_monitors(keyword)`,
      `CREATE INDEX IF NOT EXISTS intelligence_monitors_next_run_at_idx ON intelligence_monitors(next_run_at)`,
      `CREATE TABLE IF NOT EXISTS intelligence_reports (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        title TEXT NOT NULL,
        audience TEXT,
        owner TEXT,
        range_key TEXT,
        status TEXT NOT NULL DEFAULT 'draft',
        completeness INTEGER NOT NULL DEFAULT 0,
        findings JSONB NOT NULL DEFAULT '[]',
        evidence JSONB NOT NULL DEFAULT '[]',
        markdown TEXT NOT NULL,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS intelligence_reports_tenant_id_status_idx ON intelligence_reports(tenant_id, status)`,
      `CREATE INDEX IF NOT EXISTS intelligence_reports_user_id_status_idx ON intelligence_reports(user_id, status)`,
      `CREATE INDEX IF NOT EXISTS intelligence_reports_kind_idx ON intelligence_reports(kind)`,
      `CREATE INDEX IF NOT EXISTS intelligence_reports_updated_at_idx ON intelligence_reports(updated_at)`,
      `CREATE TABLE IF NOT EXISTS comment_insights (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        intelligence_item_id TEXT,
        growth_lead_id TEXT,
        redfox_call_log_id TEXT,
        platform TEXT NOT NULL,
        source_url TEXT,
        source_external_id TEXT,
        pain_points JSONB NOT NULL DEFAULT '[]',
        intent_keywords JSONB NOT NULL DEFAULT '[]',
        demand_signals JSONB NOT NULL DEFAULT '[]',
        objections JSONB NOT NULL DEFAULT '[]',
        reply_suggestions JSONB NOT NULL DEFAULT '[]',
        raw JSONB,
        analyzed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS comment_insights_tenant_id_analyzed_at_idx ON comment_insights(tenant_id, analyzed_at)`,
      `CREATE INDEX IF NOT EXISTS comment_insights_user_id_analyzed_at_idx ON comment_insights(user_id, analyzed_at)`,
      `CREATE INDEX IF NOT EXISTS comment_insights_intelligence_item_id_idx ON comment_insights(intelligence_item_id)`,
      `CREATE INDEX IF NOT EXISTS comment_insights_growth_lead_id_idx ON comment_insights(growth_lead_id)`,
      `CREATE INDEX IF NOT EXISTS comment_insights_redfox_call_log_id_idx ON comment_insights(redfox_call_log_id)`,
      `CREATE INDEX IF NOT EXISTS comment_insights_platform_idx ON comment_insights(platform)`,
      `CREATE TABLE IF NOT EXISTS crm_import_batches (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        source_type TEXT NOT NULL,
        filename TEXT,
        status TEXT NOT NULL DEFAULT 'committed',
        mode TEXT NOT NULL DEFAULT 'local-crm-write',
        row_count INTEGER NOT NULL DEFAULT 0,
        committed_count INTEGER NOT NULL DEFAULT 0,
        skipped_count INTEGER NOT NULL DEFAULT 0,
        duplicate_count INTEGER NOT NULL DEFAULT 0,
        warning_count INTEGER NOT NULL DEFAULT 0,
        dry_run_id TEXT,
        dry_run_proof_hash TEXT,
        commit_proof_hash TEXT NOT NULL,
        rollback_token TEXT NOT NULL,
        rollback_proof_hash TEXT,
        rollback_reason TEXT,
        mapping JSONB NOT NULL DEFAULT '{}',
        quality_issues JSONB NOT NULL DEFAULT '[]',
        customer_ids JSONB NOT NULL DEFAULT '[]',
        write_tables JSONB NOT NULL DEFAULT '[]',
        external_network BOOLEAN NOT NULL DEFAULT false,
        external_crm_touched BOOLEAN NOT NULL DEFAULT false,
        committed_at DATETIME,
        rolled_back_at DATETIME,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS crm_import_batches_rollback_token_key ON crm_import_batches(rollback_token)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_owner_id_idx ON crm_import_batches(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_tenant_id_idx ON crm_import_batches(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_source_type_idx ON crm_import_batches(source_type)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_status_idx ON crm_import_batches(status)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_commit_proof_hash_idx ON crm_import_batches(commit_proof_hash)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_dry_run_id_idx ON crm_import_batches(dry_run_id)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_committed_at_idx ON crm_import_batches(committed_at)`,
      `CREATE INDEX IF NOT EXISTS crm_import_batches_rolled_back_at_idx ON crm_import_batches(rolled_back_at)`,
      `CREATE TABLE IF NOT EXISTS crm_audit_events (
        id TEXT PRIMARY KEY NOT NULL,
        owner_id TEXT NOT NULL,
        tenant_id TEXT,
        import_batch_id TEXT,
        event_type TEXT NOT NULL,
        action TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'success',
        proof_hash TEXT,
        external_network BOOLEAN NOT NULL DEFAULT false,
        external_crm_touched BOOLEAN NOT NULL DEFAULT false,
        write_tables JSONB NOT NULL DEFAULT '[]',
        read_tables JSONB NOT NULL DEFAULT '[]',
        summary TEXT,
        payload JSONB,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_owner_id_idx ON crm_audit_events(owner_id)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_tenant_id_idx ON crm_audit_events(tenant_id)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_import_batch_id_idx ON crm_audit_events(import_batch_id)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_event_type_idx ON crm_audit_events(event_type)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_action_idx ON crm_audit_events(action)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_status_idx ON crm_audit_events(status)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_proof_hash_idx ON crm_audit_events(proof_hash)`,
      `CREATE INDEX IF NOT EXISTS crm_audit_events_created_at_idx ON crm_audit_events(created_at)`,
      `CREATE TABLE IF NOT EXISTS runtime_executions (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT NOT NULL DEFAULT 'legacy-local-desktop',
        user_id TEXT NOT NULL DEFAULT 'legacy-local-user',
        relatedId TEXT NOT NULL,
        relatedType TEXT NOT NULL,
        executor TEXT NOT NULL,
        platform TEXT NOT NULL,
        taskType TEXT NOT NULL,
        accountId TEXT,
        ok BOOLEAN NOT NULL,
        status TEXT NOT NULL,
        reasonCode TEXT NOT NULL,
        userMessage TEXT NOT NULL,
        technicalMessage TEXT,
        runtimeJson JSONB NOT NULL,
        evidenceJson JSONB NOT NULL DEFAULT '[]',
        readbackJson JSONB,
        agentSSessionId TEXT,
        engineUrl TEXT,
        idempotency_key TEXT,
        request_hash TEXT,
        confirmation_id TEXT,
        auth_session_id TEXT,
        claim_token TEXT,
        claimed_at DATETIME,
        lease_expires_at DATETIME,
        attempt_count INTEGER NOT NULL DEFAULT 0,
        createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS brand_knowledge (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        title TEXT NOT NULL,
        content TEXT NOT NULL,
        type TEXT NOT NULL DEFAULT 'brand',
        tags JSONB NOT NULL DEFAULT '[]',
        source TEXT,
        metadata JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS brand_knowledge_user_id_created_at_idx ON brand_knowledge(user_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS brand_knowledge_user_id_type_idx ON brand_knowledge(user_id, type)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS runtime_executions_tenant_user_task_idempotency_key ON runtime_executions(tenant_id, user_id, taskType, idempotency_key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS runtime_executions_durable_publish_related_id_key ON runtime_executions(tenant_id, user_id, relatedId) WHERE taskType = 'auto-upload-publish-record-v1'`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_relatedId_idx ON runtime_executions(relatedId)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_tenant_id_user_id_taskType_createdAt_idx ON runtime_executions(tenant_id, user_id, taskType, createdAt)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_taskType_status_lease_expires_at_createdAt_idx ON runtime_executions(taskType, status, lease_expires_at, createdAt)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_accountId_idx ON runtime_executions(accountId)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_executor_idx ON runtime_executions(executor)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_status_idx ON runtime_executions(status)`,
      `CREATE INDEX IF NOT EXISTS runtime_executions_createdAt_idx ON runtime_executions(createdAt)`,
      `CREATE TABLE IF NOT EXISTS solution_runs (
        id TEXT PRIMARY KEY NOT NULL,
        tenant_id TEXT,
        user_id TEXT NOT NULL,
        package_code TEXT NOT NULL,
        package_name TEXT NOT NULL,
        package_version TEXT NOT NULL DEFAULT '2026-07-01',
        catalog_snapshot_hash TEXT,
        trigger TEXT NOT NULL DEFAULT 'manual',
        source TEXT NOT NULL DEFAULT 'solutions',
        parent_run_id TEXT,
        correlation_id TEXT,
        idempotency_key TEXT,
        status TEXT NOT NULL DEFAULT 'planned',
        progress INTEGER NOT NULL DEFAULT 0,
        started_at DATETIME,
        ended_at DATETIME,
        duration_ms INTEGER,
        error_code TEXT,
        error_message TEXT,
        input_json JSONB NOT NULL DEFAULT '{}',
        resolved_plan_json JSONB NOT NULL DEFAULT '{}',
        data_object_mapping JSONB NOT NULL DEFAULT '{}',
        risk_level TEXT NOT NULL DEFAULT 'medium',
        confirmation_policy TEXT NOT NULL DEFAULT 'manual_required',
        send_mode TEXT NOT NULL DEFAULT 'approval-send',
        dry_run BOOLEAN NOT NULL DEFAULT true,
        estimated_cost_points INTEGER NOT NULL DEFAULT 0,
        max_cost_points INTEGER NOT NULL DEFAULT 0,
        actual_cost_points INTEGER NOT NULL DEFAULT 0,
        cost_status TEXT NOT NULL DEFAULT 'estimated',
        summary_json JSONB NOT NULL DEFAULT '{}',
        output_refs JSONB NOT NULL DEFAULT '[]',
        acceptance_checks JSONB NOT NULL DEFAULT '[]',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS solution_tasks (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL,
        step_key TEXT NOT NULL,
        "order" INTEGER NOT NULL,
        name TEXT NOT NULL,
        type TEXT NOT NULL DEFAULT 'workflow_step',
        executor_kind TEXT NOT NULL DEFAULT 'manual',
        status TEXT NOT NULL DEFAULT 'planned',
        depends_on JSONB NOT NULL DEFAULT '[]',
        attempt INTEGER NOT NULL DEFAULT 0,
        max_attempts INTEGER NOT NULL DEFAULT 1,
        retry_policy JSONB,
        queued_at DATETIME,
        started_at DATETIME,
        ended_at DATETIME,
        duration_ms INTEGER,
        input_json JSONB NOT NULL DEFAULT '{}',
        output_json JSONB,
        target_object TEXT,
        reason_code TEXT,
        error_message TEXT,
        runtime_execution_id TEXT,
        redfox_call_log_id TEXT,
        interaction_task_id TEXT,
        agent_session_id TEXT,
        agent_confirmation_id TEXT,
        intelligence_monitor_id TEXT,
        dedupe_key TEXT,
        request_hash TEXT,
        idempotency_key TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS solution_results (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL,
        task_id TEXT,
        kind TEXT NOT NULL DEFAULT 'summary',
        status TEXT NOT NULL DEFAULT 'created',
        business_object_refs JSONB NOT NULL DEFAULT '[]',
        counts JSONB NOT NULL DEFAULT '{}',
        readback JSONB,
        quality_score INTEGER,
        completeness INTEGER,
        next_action TEXT,
        failure_reason TEXT,
        accepted_at DATETIME,
        approved_by TEXT,
        payload_summary JSONB,
        raw_result_json JSONB,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS solution_artifacts (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL,
        task_id TEXT,
        result_id TEXT,
        kind TEXT NOT NULL,
        uri TEXT,
        path TEXT,
        mime_type TEXT,
        size_bytes INTEGER,
        checksum TEXT,
        label TEXT,
        preview JSONB,
        source TEXT,
        object_ref JSONB,
        pii_level TEXT NOT NULL DEFAULT 'none',
        redaction_status TEXT NOT NULL DEFAULT 'not_required',
        retention_policy TEXT,
        metadata JSONB,
        created_by TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE IF NOT EXISTS solution_cost_entries (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL,
        task_id TEXT,
        provider TEXT NOT NULL DEFAULT 'redfox',
        operation TEXT,
        skill_code TEXT,
        endpoint TEXT,
        estimated_cost_points INTEGER NOT NULL DEFAULT 0,
        authorized_cost_points INTEGER NOT NULL DEFAULT 0,
        captured_cost_points INTEGER NOT NULL DEFAULT 0,
        refunded_cost_points INTEGER NOT NULL DEFAULT 0,
        billing_status TEXT NOT NULL DEFAULT 'estimated',
        reservation_id TEXT,
        transaction_id TEXT,
        policy_version TEXT,
        request_hash TEXT,
        idempotency_key TEXT,
        latency_ms INTEGER,
        retry_count INTEGER NOT NULL DEFAULT 0,
        redfox_call_log_id TEXT,
        runtime_execution_id TEXT,
        error_code TEXT,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE INDEX IF NOT EXISTS solution_runs_tenant_id_status_idx ON solution_runs(tenant_id, status)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_tenant_id_created_at_idx ON solution_runs(tenant_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_user_id_created_at_idx ON solution_runs(user_id, created_at)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_package_code_idx ON solution_runs(package_code)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_status_idx ON solution_runs(status)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_correlation_id_idx ON solution_runs(correlation_id)`,
      `CREATE INDEX IF NOT EXISTS solution_runs_idempotency_key_idx ON solution_runs(idempotency_key)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS solution_tasks_run_id_order_key ON solution_tasks(run_id, "order")`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_run_id_status_idx ON solution_tasks(run_id, status)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_status_idx ON solution_tasks(status)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_executor_kind_idx ON solution_tasks(executor_kind)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_redfox_call_log_id_idx ON solution_tasks(redfox_call_log_id)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_runtime_execution_id_idx ON solution_tasks(runtime_execution_id)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_interaction_task_id_idx ON solution_tasks(interaction_task_id)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_agent_confirmation_id_idx ON solution_tasks(agent_confirmation_id)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_dedupe_key_idx ON solution_tasks(dedupe_key)`,
      `CREATE INDEX IF NOT EXISTS solution_tasks_request_hash_idx ON solution_tasks(request_hash)`,
      `CREATE INDEX IF NOT EXISTS solution_results_run_id_idx ON solution_results(run_id)`,
      `CREATE INDEX IF NOT EXISTS solution_results_task_id_idx ON solution_results(task_id)`,
      `CREATE INDEX IF NOT EXISTS solution_results_kind_idx ON solution_results(kind)`,
      `CREATE INDEX IF NOT EXISTS solution_results_status_idx ON solution_results(status)`,
      `CREATE INDEX IF NOT EXISTS solution_results_created_at_idx ON solution_results(created_at)`,
      `CREATE INDEX IF NOT EXISTS solution_artifacts_run_id_idx ON solution_artifacts(run_id)`,
      `CREATE INDEX IF NOT EXISTS solution_artifacts_task_id_idx ON solution_artifacts(task_id)`,
      `CREATE INDEX IF NOT EXISTS solution_artifacts_result_id_idx ON solution_artifacts(result_id)`,
      `CREATE INDEX IF NOT EXISTS solution_artifacts_kind_idx ON solution_artifacts(kind)`,
      `CREATE INDEX IF NOT EXISTS solution_artifacts_created_at_idx ON solution_artifacts(created_at)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_run_id_idx ON solution_cost_entries(run_id)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_task_id_idx ON solution_cost_entries(task_id)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_provider_idx ON solution_cost_entries(provider)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_skill_code_idx ON solution_cost_entries(skill_code)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_endpoint_idx ON solution_cost_entries(endpoint)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_billing_status_idx ON solution_cost_entries(billing_status)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_redfox_call_log_id_idx ON solution_cost_entries(redfox_call_log_id)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_runtime_execution_id_idx ON solution_cost_entries(runtime_execution_id)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_request_hash_idx ON solution_cost_entries(request_hash)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_idempotency_key_idx ON solution_cost_entries(idempotency_key)`,
      `CREATE INDEX IF NOT EXISTS solution_cost_entries_created_at_idx ON solution_cost_entries(created_at)`,
    ];

    for (const statement of statements) {
      if (this.isSqliteIndexStatement(statement)) {
        continue;
      }
      await this.$executeRawUnsafe(statement);
    }

    for (const column of [
      ['app_install_states', 'tenant_id', 'TEXT'],
      ['app_install_states', 'actor_user_id', 'TEXT'],
      ['crm_companies', 'tenant_id', 'TEXT'],
      ['crm_customers', 'tenant_id', 'TEXT'],
      ['crm_customers', 'company_id', 'TEXT'],
      ['crm_customers', 'title', 'TEXT'],
      ['crm_customers', 'email', 'TEXT'],
      ['crm_customers', 'phone', 'TEXT'],
      ['crm_customers', 'wechat', 'TEXT'],
      ['crm_opportunities', 'tenant_id', 'TEXT'],
      ['crm_tasks', 'tenant_id', 'TEXT'],
      ['crm_notes', 'tenant_id', 'TEXT'],
      ['crm_timeline_events', 'tenant_id', 'TEXT'],
      ['crm_timeline_events', 'company_id', 'TEXT'],
      ['crm_timeline_events', 'opportunity_id', 'TEXT'],
      ['crm_timeline_events', 'task_id', 'TEXT'],
      ['crm_timeline_events', 'note_id', 'TEXT'],
      ['articles', 'tenant_id', "TEXT NOT NULL DEFAULT 'legacy-local-desktop'"],
      ['articles', 'user_id', "TEXT NOT NULL DEFAULT 'legacy-local-user'"],
      ['articles', 'wechat_data', 'JSONB'],
      ['articles', 'workspace_brief', 'JSONB'],
      ['articles', 'workspace_outline', 'JSONB'],
      ['articles', 'workspace_step', "TEXT NOT NULL DEFAULT 'brief'"],
      ['articles', 'workspace_revision', 'INTEGER NOT NULL DEFAULT 1'],
      [
        'publish_accounts',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'publish_accounts',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      ['publish_accounts', 'status', "TEXT NOT NULL DEFAULT 'ready'"],
      [
        'publish_records',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'publish_records',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      ['publish_records', 'durable_record_id', 'TEXT'],
      ['publish_records', 'source_identity', 'JSONB'],
      ['publish_records', 'body_snapshot', 'TEXT'],
      ['publish_records', 'payload_json', 'JSONB'],
      ['publish_records', 'result_json', 'JSONB'],
      [
        'local_engine_reply_rules',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'local_engine_reply_rules',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      ['local_engine_reply_rules', 'bot_key', "TEXT NOT NULL DEFAULT ''"],
      [
        'local_engine_reply_rules',
        'config_version',
        'INTEGER NOT NULL DEFAULT 1',
      ],
      ['local_engine_reply_rules', 'revision', 'INTEGER NOT NULL DEFAULT 1'],
      ['local_engine_reply_rules', 'created_at', 'DATETIME'],
      ['local_engine_reply_rules', 'name', 'TEXT'],
      ['local_engine_reply_rules', 'industry', 'TEXT'],
      ['local_engine_reply_rules', 'tone', 'TEXT'],
      ['local_engine_reply_rules', 'send_mode', 'TEXT'],
      ['local_engine_reply_rules', 'keywords', "JSONB NOT NULL DEFAULT '[]'"],
      [
        'local_engine_reply_rules',
        'forbidden_words',
        "JSONB NOT NULL DEFAULT '[]'",
      ],
      ['local_engine_reply_rules', 'highlights', "JSONB NOT NULL DEFAULT '[]'"],
      ['local_engine_reply_rules', 'closing_text', 'TEXT'],
      ['local_engine_reply_rules', 'escalation_rules', 'JSONB'],
      ['local_engine_reply_rules', 'enabled', 'BOOLEAN NOT NULL DEFAULT true'],
      [
        'local_engine_agent_sessions',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'local_engine_agent_sessions',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      ['local_engine_agent_sessions', 'scope', 'TEXT'],
      ['local_engine_agent_sessions', 'target_app', 'TEXT'],
      ['local_engine_agent_sessions', 'instruction', 'TEXT'],
      ['local_engine_agent_sessions', 'risk_level', 'TEXT'],
      ['local_engine_agent_sessions', 'events', "JSONB DEFAULT '[]'"],
      ['local_engine_agent_sessions', 'confirmations', "JSONB DEFAULT '[]'"],
      ['local_engine_agent_sessions', 'evidence', "JSONB DEFAULT '[]'"],
      [
        'local_engine_agent_confirmations',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'local_engine_agent_confirmations',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      [
        'local_engine_agent_confirmations',
        'action',
        "TEXT NOT NULL DEFAULT ''",
      ],
      ['local_engine_agent_confirmations', 'target', 'TEXT'],
      ['local_engine_agent_confirmations', 'target_label', 'TEXT'],
      ['local_engine_agent_confirmations', 'content', 'TEXT'],
      ['local_engine_agent_confirmations', 'reply_text', 'TEXT'],
      ['local_engine_agent_confirmations', 'operator', 'TEXT'],
      ['local_engine_agent_confirmations', 'note', 'TEXT'],
      [
        'interaction_tasks',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'interaction_tasks',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      [
        'runtime_executions',
        'tenant_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-desktop'",
      ],
      [
        'runtime_executions',
        'user_id',
        "TEXT NOT NULL DEFAULT 'legacy-local-user'",
      ],
      ['runtime_executions', 'idempotency_key', 'TEXT'],
      ['runtime_executions', 'request_hash', 'TEXT'],
      ['runtime_executions', 'confirmation_id', 'TEXT'],
      ['runtime_executions', 'auth_session_id', 'TEXT'],
      ['runtime_executions', 'claim_token', 'TEXT'],
      ['runtime_executions', 'claimed_at', 'DATETIME'],
      ['runtime_executions', 'lease_expires_at', 'DATETIME'],
      [
        'runtime_executions',
        'attempt_count',
        'INTEGER NOT NULL DEFAULT 0',
      ],
      [
        'runtime_executions',
        'updated_at',
        'DATETIME',
      ],
    ] as const) {
      await this.ensureSqliteColumn(column[0], column[1], column[2]);
    }

    await this.$executeRawUnsafe(
      `UPDATE local_engine_reply_rules
       SET bot_key = id
       WHERE bot_key IS NULL OR TRIM(bot_key) = ''`,
    );
    await this.$executeRawUnsafe(
      `UPDATE local_engine_reply_rules
       SET created_at = COALESCE(created_at, updated_at, CURRENT_TIMESTAMP)
       WHERE created_at IS NULL`,
    );

    await this.repairSqliteNullTimestamps();
    await this.repairUnsupportedSqliteTimestampColumns();

    for (const statement of statements) {
      if (!this.isSqliteIndexStatement(statement)) {
        continue;
      }
      await this.$executeRawUnsafe(statement);
    }
  }

  private isSqliteIndexStatement(statement: string) {
    return /^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\b/i.test(statement);
  }

  private async ensureSqliteColumn(
    tableName: string,
    columnName: string,
    definition: string,
  ) {
    const columns = await this.$queryRawUnsafe<Array<{ name: string }>>(
      `PRAGMA table_info(${tableName})`,
    );
    if (columns.some((column) => column.name === columnName)) {
      return;
    }
    await this.$executeRawUnsafe(
      `ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${definition}`,
    );
  }

  private async repairSqliteNullTimestamps() {
    const tables = await this.$queryRawUnsafe<Array<{ name: string }>>(
      `SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`,
    );

    for (const table of tables) {
      const tableName = this.quoteSqliteIdentifier(table.name);
      const columns = await this.$queryRawUnsafe<Array<{ name: string }>>(
        `PRAGMA table_info(${tableName})`,
      );
      const names = new Set(columns.map((column) => column.name));
      const updatedColumn = names.has('updatedAt')
        ? 'updatedAt'
        : names.has('updated_at')
          ? 'updated_at'
          : null;
      if (!updatedColumn) continue;

      const createdColumn = names.has('createdAt')
        ? 'createdAt'
        : names.has('created_at')
          ? 'created_at'
          : null;
      const fallback = createdColumn
        ? `COALESCE("${createdColumn}", CURRENT_TIMESTAMP)`
        : 'CURRENT_TIMESTAMP';
      await this.$executeRawUnsafe(
        `UPDATE ${tableName} SET "${updatedColumn}" = ${fallback} WHERE "${updatedColumn}" IS NULL`,
      );
    }
  }

  private async repairUnsupportedSqliteTimestampColumns() {
    const tables = await this.$queryRawUnsafe<
      Array<{ name: string; sql: string | null }>
    >(
      `SELECT name, sql FROM sqlite_master WHERE type = 'table' AND sql LIKE '%TIMESTAMP(3)%'`,
    );
    for (const table of tables) {
      if (!table.sql || table.name.startsWith('sqlite_')) {
        continue;
      }
      await this.rebuildSqliteTableWithDatetimeColumns(table.name, table.sql);
    }
  }

  private async rebuildSqliteTableWithDatetimeColumns(
    tableName: string,
    createSql: string,
  ) {
    const tempTable = `${tableName}__datetime_repair`;
    const quotedTable = this.quoteSqliteIdentifier(tableName);
    const quotedTempTable = this.quoteSqliteIdentifier(tempTable);
    const columns = await this.$queryRawUnsafe<Array<{ name: string }>>(
      `PRAGMA table_info(${quotedTable})`,
    );
    const columnList = columns
      .map((column) => this.quoteSqliteIdentifier(column.name))
      .join(', ');
    if (!columnList) {
      return;
    }

    const indexes = await this.$queryRawUnsafe<Array<{ sql: string | null }>>(
      `SELECT sql FROM sqlite_master WHERE type = 'index' AND tbl_name = ? AND sql IS NOT NULL`,
      tableName,
    );
    const repairedCreateSql = createSql
      .replace(
        /^CREATE TABLE\s+(?:IF NOT EXISTS\s+)?(?:"[^"]+"|\S+)/i,
        `CREATE TABLE ${quotedTempTable}`,
      )
      .replace(/TIMESTAMP\(3\)/gi, 'DATETIME');

    this.logger.warn(
      `修复 SQLite 表 ${tableName} 的 TIMESTAMP(3) 列类型为 DATETIME`,
    );
    await this.$executeRawUnsafe('PRAGMA foreign_keys = OFF');
    try {
      await this.$executeRawUnsafe(`DROP TABLE IF EXISTS ${quotedTempTable}`);
      await this.$executeRawUnsafe(repairedCreateSql);
      await this.$executeRawUnsafe(
        `INSERT INTO ${quotedTempTable} (${columnList}) SELECT ${columnList} FROM ${quotedTable}`,
      );
      await this.$executeRawUnsafe(`DROP TABLE ${quotedTable}`);
      await this.$executeRawUnsafe(
        `ALTER TABLE ${quotedTempTable} RENAME TO ${quotedTable}`,
      );
      for (const index of indexes) {
        if (index.sql) {
          await this.$executeRawUnsafe(index.sql);
        }
      }
    } finally {
      await this.$executeRawUnsafe('PRAGMA foreign_keys = ON');
    }
  }

  private quoteSqliteIdentifier(value: string) {
    return `"${value.replace(/"/g, '""')}"`;
  }
}
