"use client";

import React from "react";
import {
  AlertTriangle,
  AppWindow,
  ArrowLeft,
  ArrowRight,
  Bolt,
  CalendarClock,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  ClipboardList,
  Cloud,
  CloudDownload,
  Code,
  Copy,
  Cpu,
  Download,
  Eye,
  File,
  FilePlus,
  FileText,
  Folder,
  FolderOpen,
  FolderX,
  Globe,
  Handshake,
  Home,
  Image,
  Images,
  Inbox,
  KeyRound,
  Laptop,
  LayoutDashboard,
  Mail,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Monitor,
  PauseCircle,
  PenLine,
  PlayCircle,
  Plug,
  PlusCircle,
  Radio,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Save,
  Search,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SkipForward,
  Sparkles,
  SquareCheck,
  Star,
  StopCircle,
  Trash2,
  Upload,
  UserCheck,
  Video,
  WandSparkles,
  Wrench,
  XCircle,
  type LucideIcon,
} from "lucide-react";

type CompatIconProps = Omit<React.ComponentProps<LucideIcon>, "ref"> & {
  icon: string;
  width?: number | string;
  height?: number | string;
};

const ICON_MAP: Record<string, LucideIcon> = {
  "fa-brands:weixin": MessageCircle,
  "solar:add-circle-bold": PlusCircle,
  "solar:add-circle-linear": PlusCircle,
  "solar:alt-arrow-down-linear": ChevronDown,
  "solar:alt-arrow-right-linear": ChevronRight,
  "solar:alt-arrow-up-linear": ChevronUp,
  "solar:arrow-left-linear": ArrowLeft,
  "solar:arrow-right-linear": ArrowRight,
  "solar:bolt-bold-duotone": Bolt,
  "solar:bolt-linear": Bolt,
  "solar:chat-round-dots-bold": MessageCircle,
  "solar:chat-round-dots-linear": MessageCircle,
  "solar:chat-round-like-linear": MessageCircle,
  "solar:chat-round-line-linear": MessageCircle,
  "solar:chat-square-check-linear": MessageSquare,
  "solar:check-circle-bold": CheckCircle,
  "solar:check-circle-linear": CheckCircle,
  "solar:check-read-linear": CheckCircle,
  "solar:check-square-linear": SquareCheck,
  "solar:clipboard-list-linear": ClipboardList,
  "solar:clock-circle-linear": CalendarClock,
  "solar:close-circle-linear": XCircle,
  "solar:cloud-download-linear": CloudDownload,
  "solar:cloud-line-duotone": Cloud,
  "solar:cloud-storage-bold": Cloud,
  "solar:code-square-linear": Code,
  "solar:copy-bold": Copy,
  "solar:copy-linear": Copy,
  "solar:cpu-bold": Cpu,
  "solar:cpu-bolt-linear": Cpu,
  "solar:danger-triangle-linear": AlertTriangle,
  "solar:devices-linear": Laptop,
  "solar:dialog-2-linear": MessagesSquare,
  "solar:diskette-bold": Save,
  "solar:diskette-linear": Save,
  "solar:document-add-bold": FilePlus,
  "solar:document-add-linear": FilePlus,
  "solar:document-linear": FileText,
  "solar:document-text-broken": FileText,
  "solar:document-text-linear": FileText,
  "solar:download-minimalistic-bold": Download,
  "solar:download-minimalistic-linear": Download,
  "solar:external-link-linear": ArrowRight,
  "solar:eye-bold": Eye,
  "solar:eye-linear": Eye,
  "solar:file-linear": File,
  "solar:file-text-linear": FileText,
  "solar:folder-error-bold-duotone": FolderX,
  "solar:folder-linear": Folder,
  "solar:folder-with-files-linear": FolderOpen,
  "solar:forward-2-linear": SkipForward,
  "solar:gallery-bold": Images,
  "solar:gallery-bold-duotone": Images,
  "solar:gallery-check-linear": Images,
  "solar:gallery-linear": Image,
  "solar:gallery-remove-broken": Images,
  "solar:global-bold": Globe,
  "solar:global-linear": Globe,
  "solar:hand-shake-linear": Handshake,
  "solar:home-2-linear": Home,
  "solar:inbox-line-linear": Inbox,
  "solar:info-circle-linear": CircleAlert,
  "solar:key-minimalistic-square-linear": KeyRound,
  "solar:letter-linear": Mail,
  "solar:magic-stick-3-bold-duotone": WandSparkles,
  "solar:magic-stick-3-linear": WandSparkles,
  "solar:magnifer-linear": Search,
  "solar:monitor-linear": Monitor,
  "solar:pause-circle-linear": PauseCircle,
  "solar:pen-bold": PenLine,
  "solar:pen-linear": PenLine,
  "solar:pen-new-square-bold-duotone": PenLine,
  "solar:pen-new-square-linear": PenLine,
  "solar:play-circle-linear": PlayCircle,
  "solar:plug-connected-linear": Plug,
  "solar:programming-bold": Code,
  "solar:radio-linear": Radio,
  "solar:refresh-circle-linear": RefreshCw,
  "solar:refresh-linear": RefreshCw,
  "solar:restart-circle-linear": RotateCcw,
  "solar:restart-linear": RotateCcw,
  "solar:round-transfer-diagonal-bold": Repeat2,
  "solar:round-transfer-diagonal-linear": Repeat2,
  "solar:send-linear": Send,
  "solar:send-square-linear": SendHorizontal,
  "solar:server-bold-duotone": Server,
  "solar:server-square-cloud-linear": Server,
  "solar:settings-linear": Settings,
  "solar:settings-minimalistic-linear": Settings,
  "solar:settings-outline": Settings,
  "solar:share-circle-linear": Share2,
  "solar:shield-check-linear": ShieldCheck,
  "solar:shield-linear": Shield,
  "solar:shield-warning-linear": ShieldAlert,
  "solar:skip-forward-linear": SkipForward,
  "solar:skip-next-linear": SkipForward,
  "solar:star-bold": Star,
  "solar:star-outline": Star,
  "solar:stars-minimalistic-linear": Sparkles,
  "solar:stop-circle-linear": StopCircle,
  "solar:trash-bin-minimalistic-linear": Trash2,
  "solar:trash-bin-trash-bold": Trash2,
  "solar:trash-bin-trash-linear": Trash2,
  "solar:upload-linear": Upload,
  "solar:upload-minimalistic-linear": Upload,
  "solar:user-check-linear": UserCheck,
  "solar:video-frame-bold-duotone": Video,
  "solar:video-library-linear": Video,
  "solar:videocamera-record-linear": Video,
  "solar:widget-2-outline": LayoutDashboard,
  "solar:widget-linear": LayoutDashboard,
  "solar:window-frame-linear": AppWindow,
  "solar:wrench-linear": Wrench,
};

export function Icon({ icon, width, height, size, className, strokeWidth = 1.75, style, ...props }: CompatIconProps) {
  const LucideIcon = ICON_MAP[icon] ?? Circle;
  const iconSize = size ?? (typeof width === "number" ? width : typeof height === "number" ? height : 18);

  return (
    <LucideIcon
      aria-hidden="true"
      className={className}
      size={iconSize}
      strokeWidth={strokeWidth}
      style={{
        ...style,
        ...(typeof width === "string" ? { width } : null),
        ...(typeof height === "string" ? { height } : null),
      }}
      {...props}
    />
  );
}

export function loadIcons(_names?: ReadonlyArray<string>) {
  void _names;
  return Promise.resolve();
}
