CREATE INDEX IF NOT EXISTS users_kaypal_user_id_idx ON users(kaypal_user_id);
CREATE INDEX IF NOT EXISTS billing_subscriptions_tenant_id_idx ON billing_subscriptions(tenant_id);
CREATE INDEX IF NOT EXISTS billing_subscriptions_provider_idx ON billing_subscriptions(provider);
CREATE INDEX IF NOT EXISTS billing_subscriptions_status_idx ON billing_subscriptions(status);
CREATE INDEX IF NOT EXISTS billing_subscriptions_plan_idx ON billing_subscriptions(plan);
CREATE INDEX IF NOT EXISTS billing_subscriptions_current_period_end_idx ON billing_subscriptions(current_period_end);
CREATE INDEX IF NOT EXISTS billing_invoices_tenant_id_idx ON billing_invoices(tenant_id);
CREATE INDEX IF NOT EXISTS billing_invoices_provider_idx ON billing_invoices(provider);
CREATE INDEX IF NOT EXISTS billing_invoices_status_idx ON billing_invoices(status);
CREATE INDEX IF NOT EXISTS billing_invoices_external_customer_id_idx ON billing_invoices(external_customer_id);
CREATE INDEX IF NOT EXISTS billing_invoices_external_subscription_id_idx ON billing_invoices(external_subscription_id);
CREATE INDEX IF NOT EXISTS billing_invoices_paid_at_idx ON billing_invoices(paid_at);
CREATE INDEX IF NOT EXISTS billing_invoices_failed_at_idx ON billing_invoices(failed_at);
CREATE INDEX IF NOT EXISTS billing_webhook_events_tenant_id_idx ON billing_webhook_events(tenant_id);
CREATE INDEX IF NOT EXISTS billing_webhook_events_provider_idx ON billing_webhook_events(provider);
CREATE INDEX IF NOT EXISTS billing_webhook_events_event_type_idx ON billing_webhook_events(event_type);
CREATE INDEX IF NOT EXISTS billing_webhook_events_status_idx ON billing_webhook_events(status);
CREATE INDEX IF NOT EXISTS billing_webhook_events_external_customer_id_idx ON billing_webhook_events(external_customer_id);
CREATE INDEX IF NOT EXISTS billing_webhook_events_external_subscription_id_idx ON billing_webhook_events(external_subscription_id);
CREATE INDEX IF NOT EXISTS billing_webhook_events_processed_at_idx ON billing_webhook_events(processed_at);
CREATE INDEX IF NOT EXISTS content_strategies_is_default_idx ON content_strategies(is_default);
CREATE INDEX IF NOT EXISTS content_strategies_enabled_idx ON content_strategies(enabled);
CREATE INDEX IF NOT EXISTS content_strategy_templates_industry_type_idx ON content_strategy_templates(industry, type);
CREATE INDEX IF NOT EXISTS content_strategy_templates_enabled_idx ON content_strategy_templates(enabled);
CREATE INDEX IF NOT EXISTS materials_owner_id_platform_idx ON materials(owner_id, platform);
CREATE INDEX IF NOT EXISTS articles_parent_id_idx ON articles(parent_id);
CREATE INDEX IF NOT EXISTS compliance_checks_tenant_id_checked_at_idx ON compliance_checks(tenant_id, checked_at);
CREATE INDEX IF NOT EXISTS compliance_checks_user_id_checked_at_idx ON compliance_checks(user_id, checked_at);
CREATE INDEX IF NOT EXISTS compliance_checks_material_id_idx ON compliance_checks(material_id);
CREATE INDEX IF NOT EXISTS compliance_checks_topic_id_idx ON compliance_checks(topic_id);
CREATE INDEX IF NOT EXISTS compliance_checks_redfox_call_log_id_idx ON compliance_checks(redfox_call_log_id);
CREATE INDEX IF NOT EXISTS compliance_checks_target_type_target_id_idx ON compliance_checks(target_type, target_id);
CREATE INDEX IF NOT EXISTS compliance_checks_platform_idx ON compliance_checks(platform);
CREATE INDEX IF NOT EXISTS compliance_checks_risk_level_idx ON compliance_checks(risk_level);
CREATE INDEX IF NOT EXISTS compliance_checks_status_idx ON compliance_checks(status);
CREATE INDEX IF NOT EXISTS content_drafts_user_id_updated_at_idx ON content_drafts(user_id, updated_at);
CREATE INDEX IF NOT EXISTS content_drafts_tenant_id_updated_at_idx ON content_drafts(tenant_id, updated_at);
CREATE INDEX IF NOT EXISTS content_optimization_runs_draft_id_created_at_idx ON content_optimization_runs(draft_id, created_at);
CREATE INDEX IF NOT EXISTS content_optimization_runs_user_id_updated_at_idx ON content_optimization_runs(user_id, updated_at);
CREATE INDEX IF NOT EXISTS content_versions_user_id_updated_at_idx ON content_versions(user_id, updated_at);
CREATE INDEX IF NOT EXISTS content_versions_tenant_id_updated_at_idx ON content_versions(tenant_id, updated_at);
CREATE INDEX IF NOT EXISTS content_versions_draft_id_version_no_idx ON content_versions(draft_id, version_no);
CREATE INDEX IF NOT EXISTS content_versions_status_idx ON content_versions(status);
CREATE INDEX IF NOT EXISTS content_versions_is_official_idx ON content_versions(is_official);
CREATE INDEX IF NOT EXISTS content_publish_intents_version_id_idx ON content_publish_intents(version_id);
CREATE INDEX IF NOT EXISTS content_publish_intents_user_id_created_at_idx ON content_publish_intents(user_id, created_at);
CREATE INDEX IF NOT EXISTS content_manual_reviews_version_id_created_at_idx ON content_manual_reviews(version_id, created_at);
CREATE INDEX IF NOT EXISTS content_manual_reviews_user_id_created_at_idx ON content_manual_reviews(user_id, created_at);
CREATE INDEX IF NOT EXISTS content_publish_feedback_version_id_created_at_idx ON content_publish_feedback(version_id, created_at);
CREATE INDEX IF NOT EXISTS content_publish_feedback_user_id_created_at_idx ON content_publish_feedback(user_id, created_at);
CREATE INDEX IF NOT EXISTS content_version_comments_version_id_created_at_idx ON content_version_comments(version_id, created_at);
CREATE INDEX IF NOT EXISTS content_version_comments_user_id_created_at_idx ON content_version_comments(user_id, created_at);
CREATE INDEX IF NOT EXISTS content_evidence_logs_target_type_target_id_idx ON content_evidence_logs(target_type, target_id);
CREATE INDEX IF NOT EXISTS content_evidence_logs_user_id_created_at_idx ON content_evidence_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS interaction_tasks_sourceArticleId_idx ON interaction_tasks(sourceArticleId);
CREATE INDEX IF NOT EXISTS interaction_tasks_publishRecordId_idx ON interaction_tasks(publishRecordId);
CREATE INDEX IF NOT EXISTS interaction_events_identity_id_idx ON interaction_events(identity_id);
CREATE INDEX IF NOT EXISTS interaction_events_content_id_idx ON interaction_events(content_id);
CREATE INDEX IF NOT EXISTS interaction_events_parent_event_id_idx ON interaction_events(parent_event_id);
CREATE INDEX IF NOT EXISTS wecom_corp_configs_user_id_idx ON wecom_corp_configs(user_id);
CREATE INDEX IF NOT EXISTS wecom_corp_configs_status_idx ON wecom_corp_configs(status);
CREATE INDEX IF NOT EXISTS wecom_group_msg_tasks_user_id_idx ON wecom_group_msg_tasks(user_id);
CREATE INDEX IF NOT EXISTS wecom_group_msg_tasks_config_id_idx ON wecom_group_msg_tasks(config_id);
CREATE INDEX IF NOT EXISTS wecom_group_msg_tasks_wecom_msg_id_idx ON wecom_group_msg_tasks(wecom_msg_id);
CREATE INDEX IF NOT EXISTS wecom_moment_tasks_user_id_idx ON wecom_moment_tasks(user_id);
CREATE INDEX IF NOT EXISTS wecom_moment_tasks_config_id_idx ON wecom_moment_tasks(config_id);
CREATE INDEX IF NOT EXISTS wecom_moment_tasks_wecom_job_id_idx ON wecom_moment_tasks(wecom_job_id);
CREATE INDEX IF NOT EXISTS wecom_contacts_config_id_idx ON wecom_contacts(config_id);
CREATE INDEX IF NOT EXISTS boss_accounts_user_id_idx ON boss_accounts(user_id);
CREATE INDEX IF NOT EXISTS boss_candidates_user_id_idx ON boss_candidates(user_id);
CREATE INDEX IF NOT EXISTS boss_candidates_account_id_idx ON boss_candidates(account_id);
CREATE INDEX IF NOT EXISTS boss_tasks_user_id_idx ON boss_tasks(user_id);
CREATE INDEX IF NOT EXISTS boss_tasks_account_id_idx ON boss_tasks(account_id);
CREATE INDEX IF NOT EXISTS boss_tasks_status_idx ON boss_tasks(status);
CREATE INDEX IF NOT EXISTS growth_strategies_user_id_idx ON growth_strategies(user_id);
CREATE INDEX IF NOT EXISTS growth_strategies_tenant_id_idx ON growth_strategies(tenant_id);
CREATE INDEX IF NOT EXISTS growth_acquisition_configs_user_id_status_idx ON growth_acquisition_configs(user_id, status);
CREATE INDEX IF NOT EXISTS growth_acquisition_configs_user_id_schedule_enabled_idx ON growth_acquisition_configs(user_id, schedule_enabled);
CREATE INDEX IF NOT EXISTS growth_acquisition_configs_tenant_id_status_idx ON growth_acquisition_configs(tenant_id, status);
CREATE INDEX IF NOT EXISTS growth_acquisition_configs_tenant_id_schedule_enabled_idx ON growth_acquisition_configs(tenant_id, schedule_enabled);
CREATE INDEX IF NOT EXISTS growth_acquisition_configs_platform_account_id_idx ON growth_acquisition_configs(platform, account_id);
CREATE INDEX IF NOT EXISTS growth_acquisition_runs_user_id_started_at_idx ON growth_acquisition_runs(user_id, started_at);
CREATE INDEX IF NOT EXISTS growth_acquisition_runs_tenant_id_started_at_idx ON growth_acquisition_runs(tenant_id, started_at);
CREATE INDEX IF NOT EXISTS growth_acquisition_runs_config_id_started_at_idx ON growth_acquisition_runs(config_id, started_at);
CREATE INDEX IF NOT EXISTS growth_leads_user_id_status_idx ON growth_leads(user_id, status);
CREATE INDEX IF NOT EXISTS growth_leads_user_id_platform_idx ON growth_leads(user_id, platform);
CREATE INDEX IF NOT EXISTS growth_leads_tenant_id_status_idx ON growth_leads(tenant_id, status);
CREATE INDEX IF NOT EXISTS growth_leads_tenant_id_platform_idx ON growth_leads(tenant_id, platform);
CREATE INDEX IF NOT EXISTS growth_leads_source_task_id_idx ON growth_leads(source_task_id);
CREATE INDEX IF NOT EXISTS growth_account_health_user_id_risk_status_idx ON growth_account_health(user_id, risk_status);
CREATE INDEX IF NOT EXISTS growth_account_health_tenant_id_risk_status_idx ON growth_account_health(tenant_id, risk_status);
CREATE INDEX IF NOT EXISTS growth_account_health_snapshots_user_id_platform_account_id_checked_at_idx ON growth_account_health_snapshots(user_id, platform, account_id, checked_at);
CREATE INDEX IF NOT EXISTS growth_account_health_snapshots_tenant_id_platform_account_id_idx ON growth_account_health_snapshots(tenant_id, platform, account_id);
CREATE INDEX IF NOT EXISTS growth_workflows_user_id_status_idx ON growth_workflows(user_id, status);
CREATE INDEX IF NOT EXISTS growth_workflows_tenant_id_status_idx ON growth_workflows(tenant_id, status);
CREATE INDEX IF NOT EXISTS growth_scheduler_leases_tenant_id_idx ON growth_scheduler_leases(tenant_id);
CREATE INDEX IF NOT EXISTS growth_scheduler_leases_user_id_idx ON growth_scheduler_leases(user_id);
CREATE INDEX IF NOT EXISTS growth_scheduler_leases_locked_until_idx ON growth_scheduler_leases(locked_until);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_id_idx ON push_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS brand_knowledge_tenant_id_idx ON brand_knowledge(tenant_id);
CREATE INDEX IF NOT EXISTS account_subscriptions_tenant_id_user_id_idx ON account_subscriptions(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS user_memories_user_id_type_idx ON user_memories(user_id, type);
CREATE INDEX IF NOT EXISTS user_memories_user_id_priority_idx ON user_memories(user_id, priority);
CREATE INDEX IF NOT EXISTS ai_chat_logs_user_id_created_at_idx ON ai_chat_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS ai_tool_call_logs_user_id_created_at_idx ON ai_tool_call_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS ai_call_traces_user_id_created_at_idx ON ai_call_traces(user_id, created_at);
CREATE INDEX IF NOT EXISTS ai_call_traces_scene_created_at_idx ON ai_call_traces(scene, created_at);
CREATE INDEX IF NOT EXISTS mobile_devices_user_id_idx ON mobile_devices(user_id);
CREATE INDEX IF NOT EXISTS executor_tasks_user_id_status_idx ON executor_tasks(user_id, status);
CREATE INDEX IF NOT EXISTS executor_tasks_device_id_idx ON executor_tasks(device_id);
CREATE INDEX IF NOT EXISTS offer_snapshots_vendor_code_platform_code_item_id_idx ON offer_snapshots(vendor_code, platform_code, item_id);
CREATE INDEX IF NOT EXISTS offer_snapshots_master_id_idx ON offer_snapshots(master_id);
CREATE INDEX IF NOT EXISTS price_watches_tenant_id_user_id_status_idx ON price_watches(tenant_id, user_id, status);
CREATE INDEX IF NOT EXISTS cps_promo_links_tenant_id_user_id_idx ON cps_promo_links(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS cps_orders_tenant_id_user_id_status_idx ON cps_orders(tenant_id, user_id, status);
CREATE INDEX IF NOT EXISTS rebate_ledgers_tenant_id_user_id_created_at_idx ON rebate_ledgers(tenant_id, user_id, created_at);
CREATE INDEX IF NOT EXISTS rebate_withdrawals_tenant_id_user_id_status_idx ON rebate_withdrawals(tenant_id, user_id, status);
CREATE INDEX IF NOT EXISTS rebate_exchanges_tenant_id_user_id_idx ON rebate_exchanges(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS price_histories_tenant_id_user_id_snapshot_at_idx ON price_histories(tenant_id, user_id, snapshot_at);
CREATE INDEX IF NOT EXISTS price_histories_item_id_snapshot_at_idx ON price_histories(item_id, snapshot_at);
CREATE INDEX IF NOT EXISTS stores_tenant_id_status_idx ON stores(tenant_id, status);
CREATE INDEX IF NOT EXISTS procurement_lists_tenant_id_user_id_idx ON procurement_lists(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS procurement_lists_store_id_idx ON procurement_lists(store_id);
CREATE INDEX IF NOT EXISTS cps_favorites_tenant_id_user_id_created_at_idx ON cps_favorites(tenant_id, user_id, created_at);
CREATE INDEX IF NOT EXISTS savings_checkins_tenant_id_user_id_checkin_date_idx ON savings_checkins(tenant_id, user_id, checkin_date);
CREATE INDEX IF NOT EXISTS poi_stores_tenant_id_user_id_status_idx ON poi_stores(tenant_id, user_id, status);
CREATE INDEX IF NOT EXISTS poi_stores_tenant_id_user_id_city_idx ON poi_stores(tenant_id, user_id, city);
CREATE INDEX IF NOT EXISTS exposure_accounts_user_id_idx ON exposure_accounts(user_id);
CREATE INDEX IF NOT EXISTS activation_events_tenant_id_event_type_created_at_idx ON activation_events(tenant_id, event_type, created_at);
CREATE INDEX IF NOT EXISTS source_contents_tenant_id_platform_account_id_collected_at_idx ON source_contents(tenant_id, platform, account_id, collected_at);
CREATE INDEX IF NOT EXISTS suppressions_tenant_id_kind_normalized_value_idx ON suppressions(tenant_id, kind, normalized_value);
CREATE INDEX IF NOT EXISTS lead_signals_tenant_id_type_idx ON lead_signals(tenant_id, type);
