import { ToolSpec } from './types';

/**
 * 标准工具最小集合 —— 对齐《整合 PRD》7 / 《补充包》5.2。
 * 每个工具的 risk / requiresConfirmation / evidenceTypes / idempotencyScope 均按文档设定。
 */
export const STANDARD_TOOL_SPECS: ToolSpec[] = [
  {
    name: 'content_generate',
    version: '1.0.0',
    domain: 'content',
    readOnly: false,
    risk: 'low',
    requiresConfirmation: false,
    supportsPause: true,
    supportsResume: true,
    requiredCapabilities: [],
    inputSchema: { type: 'object', properties: { title: { type: 'string' } } },
    outputSchema: { type: 'object', properties: { contentId: { type: 'string' } } },
    idempotencyScope: 'tenant+content+brief',
    evidenceTypes: ['screenshot'],
    compensation: 'discard_draft',
  },
  {
    name: 'content_review',
    version: '1.0.0',
    domain: 'content',
    readOnly: true,
    risk: 'low',
    requiresConfirmation: false,
    supportsPause: false,
    supportsResume: false,
    requiredCapabilities: [],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+content+version',
    evidenceTypes: ['text'],
    compensation: 'none',
  },
  {
    name: 'publish_execute',
    version: '1.0.0',
    domain: 'publish',
    readOnly: false,
    risk: 'high',
    requiresConfirmation: true,
    supportsPause: true,
    supportsResume: true,
    requiredCapabilities: ['rpa.browser'],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+content+platform+schedule',
    evidenceTypes: ['screenshot', 'platform_url'],
    compensation: 'cancel_schedule_or_manual_followup',
  },
  {
    name: 'interaction_reply_execute',
    version: '1.0.0',
    domain: 'interaction',
    readOnly: false,
    risk: 'high',
    requiresConfirmation: true,
    supportsPause: true,
    supportsResume: true,
    requiredCapabilities: ['rpa.browser'],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+platform+message',
    evidenceTypes: ['screenshot'],
    compensation: 'manual_followup',
  },
  {
    name: 'lead_discover',
    version: '1.0.0',
    domain: 'lead',
    readOnly: false,
    risk: 'medium',
    requiresConfirmation: false,
    supportsPause: true,
    supportsResume: true,
    requiredCapabilities: ['rpa.browser'],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+platform+query',
    evidenceTypes: ['screenshot', 'platform_url'],
    compensation: 'discard_leads',
  },
  {
    name: 'lead_normalize',
    version: '1.0.0',
    domain: 'lead',
    readOnly: false,
    risk: 'low',
    requiresConfirmation: false,
    supportsPause: false,
    supportsResume: false,
    requiredCapabilities: [],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+leadBatch',
    evidenceTypes: [],
    compensation: 'none',
  },
  {
    name: 'crm_create',
    version: '1.0.0',
    domain: 'crm',
    readOnly: false,
    risk: 'high',
    requiresConfirmation: true,
    supportsPause: true,
    supportsResume: true,
    requiredCapabilities: [],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+sourceId+phoneHash',
    evidenceTypes: ['screenshot'],
    compensation: 'revert_create',
  },
  {
    name: 'report_generate',
    version: '1.0.0',
    domain: 'review',
    readOnly: false,
    risk: 'low',
    requiresConfirmation: false,
    supportsPause: false,
    supportsResume: false,
    requiredCapabilities: [],
    inputSchema: {},
    outputSchema: {},
    idempotencyScope: 'tenant+range',
    evidenceTypes: ['screenshot'],
    compensation: 'none',
  },
];
