import type { SolutionPackageDefinition } from './solutions.types';

export const SOLUTION_PACKAGES: SolutionPackageDefinition[] = [
  {
    code: 'hot-topic-solution',
    name: '热点选题解决方案',
    category: 'core',
    implementationState: 'partial',
    summary: '把全网热点、平台爆款、AI 信息源和历史素材转成可执行选题。',
    customerValue: '让运营每天拿到可解释、可追踪、能直接进入生产流的内容机会。',
    entryPath: '/solutions/hot-topic-solution',
    connectedEntryPath: '/intelligence/trends',
    ownerGroups: [
      '产品方案组',
      'RedFox 接入组',
      '数据与工作流组',
      '内容与增长组',
    ],
    redfoxSkills: [
      '全网热搜/聚合热点',
      '抖音热门/点赞飙升',
      '小红书爆款',
      '公众号 10w+',
      'AI 信息源',
    ],
    workflow: [
      '关键词平台配置',
      'RedFox 热点采集',
      '情报入库',
      '素材沉淀',
      '选题生成',
      '内容包输出',
    ],
    dataObjects: [
      'SolutionRun',
      'IntelligenceItem',
      'Material',
      'Topic',
      'Article',
    ],
    acceptance: [
      '至少生成 10 条机会项',
      '生成 3-5 条选题入库',
      '支持定时日报和来源证据',
    ],
    estimatedWorkdays: 8,
  },
  {
    code: 'competitor-account-radar',
    name: '竞品账号雷达',
    category: 'core',
    implementationState: 'partial',
    summary: '发现并跟踪竞品账号、爆款内容、涨粉异常和可复制栏目。',
    customerValue: '让团队知道同行正在涨什么、靠什么涨、哪些打法值得跟进。',
    entryPath: '/solutions/competitor-account-radar',
    connectedEntryPath: '/intelligence/accounts',
    ownerGroups: [
      '产品方案组',
      'RedFox 接入组',
      '数据与工作流组',
      '内容与增长组',
    ],
    redfoxSkills: [
      '抖音账号搜索/热门/相似/诊断',
      '小红书账号搜索/热门/相似/诊断',
      '公众号账号搜索',
      'B 站搜账号',
      'TikTok 账号搜索',
    ],
    workflow: [
      '账号发现',
      '对标账号入库',
      '自动跟踪',
      '异常识别',
      '报告生成',
      '选题建议',
    ],
    dataObjects: [
      'SolutionRun',
      'BenchmarkAccount',
      'IntelligenceMonitor',
      'IntelligenceReport',
      'Topic',
    ],
    acceptance: [
      '可添加对标账号',
      '输出栏目/爆款/涨粉异常',
      '沉淀周报机会和原始证据',
    ],
    estimatedWorkdays: 10,
  },
  {
    code: 'comment-lead-solution',
    name: '评论获客解决方案',
    category: 'core',
    implementationState: 'partial',
    summary: '从多平台评论中识别需求、购买意图、投诉和合作机会。',
    customerValue: '把公域互动转成可跟进线索，并给客服或销售明确跟进理由。',
    entryPath: '/solutions/comment-lead-solution',
    connectedEntryPath: '/interaction/comment-insights',
    ownerGroups: ['内容与增长组', 'CRM 组', 'RedFox 接入组'],
    redfoxSkills: ['抖音评论分析', '小红书评论分析', 'B 站评论分析'],
    workflow: [
      '评论抓取',
      '评论洞察',
      '回复建议',
      '人工确认',
      'CRM 线索创建',
      '跟进任务生成',
    ],
    dataObjects: [
      'SolutionRun',
      'CommentInsight',
      'AgentConfirmation',
      'CrmCustomer',
      'CrmTask',
      'GrowthLead',
    ],
    acceptance: [
      '评论可持久化',
      '高意向进入人工确认',
      '确认后创建 CRM 线索和任务',
    ],
    estimatedWorkdays: 9,
  },
  {
    code: 'creation-enhancement',
    name: '创作增强解决方案',
    category: 'core',
    implementationState: 'partial',
    summary: '围绕标题、结构、平台语气、封面和视频提示词增强内容生产。',
    customerValue: '让内容生产从经验改稿变成样本、评分和多平台版本驱动。',
    entryPath: '/solutions/creation-enhancement',
    connectedEntryPath: '/content/optimization',
    ownerGroups: ['内容与增长组', 'AI 编排组', 'RedFox 接入组'],
    redfoxSkills: [
      '小红书标题生成评分与创作',
      '公众号标题生成评分与创作',
      '多平台改写',
      '封面制作',
      'Seedance/图片生成',
    ],
    workflow: [
      '选题输入',
      '内容简报生成',
      '多平台文案生成',
      '素材生成',
      '发布草稿生成',
    ],
    dataObjects: [
      'SolutionRun',
      'Topic',
      'Article',
      'Material',
      'PublishRecord',
      'RedfoxCallLog',
    ],
    acceptance: [
      '同题输出多平台版本',
      '标题评分调用 RedFox 能力',
      '结果写入文章/笔记/视频工坊',
    ],
    estimatedWorkdays: 8,
  },
  {
    code: 'publish-compliance',
    name: '发布合规解决方案',
    category: 'core',
    implementationState: 'partial',
    summary: '发布前检查平台违禁词、风险表达、确认流和发布证据链。',
    customerValue: '降低内容违规、账号降权和商用执行失控的概率。',
    entryPath: '/solutions/publish-compliance',
    connectedEntryPath: '/distribution/compliance',
    ownerGroups: ['风控合规组', '发布中台组', 'RedFox 接入组'],
    redfoxSkills: [
      '多平台违禁词检测',
      '抖音违禁词检测',
      '小红书违禁词检测',
      '公众号违禁词检测',
    ],
    workflow: [
      '草稿输入',
      '合规检查',
      '风险闸门',
      '人工确认',
      '发布前检查',
      '证据链记录',
    ],
    dataObjects: [
      'SolutionRun',
      'Article',
      'ComplianceCheck',
      'AgentConfirmation',
      'PublishRecord',
      'RiskEvidence',
    ],
    acceptance: [
      '高风险阻断发布',
      '命中项包含原因和替代表达',
      '合规结果进入操作证据链',
    ],
    estimatedWorkdays: 7,
  },
  {
    code: 'industry-intel',
    name: '行业情报包',
    category: 'redfox_pool',
    implementationState: 'connected',
    summary: '按行业聚合政策、热点、竞品、用户需求和内容趋势。',
    customerValue: '给运营负责人一张行业作战地图，减少分散搜索和人工周报。',
    entryPath: '/solutions/industry-intel',
    ownerGroups: ['产品方案组', '数据与工作流组'],
    redfoxSkills: [
      '文旅多平台信息源',
      '短剧多平台信息源',
      'A 股新闻/大 V/调查员',
    ],
    workflow: ['行业配置', 'RedFox 信息源采集', '情报入库', '行业报告生成'],
    dataObjects: [
      'SolutionRun',
      'IntelligenceItem',
      'IntelligenceReport',
      'Material',
    ],
    acceptance: [
      '生成日报/周报',
      '报告包含热点/机会/风险/动作建议',
      '机会可进入选题库',
    ],
    estimatedWorkdays: 6,
  },
  {
    code: 'global-content-intel',
    name: '出海内容情报包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '采集海外平台账号、内容趋势和脚本结构，转译为本地化选题。',
    customerValue: '帮助团队发现海外先发趋势，并转成国内平台可执行内容。',
    entryPath: '/solutions/global-content-intel',
    ownerGroups: ['产品方案组', '内容与增长组'],
    redfoxSkills: [
      'TikTok 账号搜索',
      '全网出海信息源',
      'AI 信息源',
      '全网热搜',
    ],
    workflow: [
      '国家品类平台配置',
      '账号内容搜索',
      '机会池沉淀',
      '脚本建议生成',
    ],
    dataObjects: [
      'SolutionRun',
      'BenchmarkAccount',
      'IntelligenceItem',
      'Topic',
      'Material',
    ],
    acceptance: ['沉淀海外账号', '沉淀热门内容和脚本结构', '生成本地化选题'],
    estimatedWorkdays: 7,
  },
  {
    code: 'low-follower-viral',
    name: '低粉爆款挖掘包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '发现低粉账号的异常爆款，拆解更适合冷启动账号复制的内容模式。',
    customerValue: '避免只学习头部账号，为新账号找到更可复制的增长实验。',
    entryPath: '/solutions/low-follower-viral',
    ownerGroups: ['数据与工作流组', '内容与增长组'],
    redfoxSkills: [
      '小红书低粉爆款',
      '小红书每日/七日爆款',
      '公众号黑马/10w+',
      '抖音涨粉/点赞榜',
    ],
    workflow: [
      '行业账号阶段配置',
      '样本采集',
      '结构拆解',
      '评论需求提取',
      '选题生成',
    ],
    dataObjects: [
      'SolutionRun',
      'IntelligenceItem',
      'Material',
      'Topic',
      'SolutionRunItem',
    ],
    acceptance: [
      '输出样本列表',
      '输出结构和评论需求',
      '生成至少 3 条可复刻选题',
    ],
    estimatedWorkdays: 6,
  },
  {
    code: 'kol-screening',
    name: '达人/KOL 筛选包',
    category: 'redfox_pool',
    implementationState: 'connected',
    summary: '按投放目标、人设、内容质量、互动质量和风险筛选合作达人。',
    customerValue: '把达人投放从人工翻账号变成可量化筛选和尽调流程。',
    entryPath: '/solutions/kol-screening',
    ownerGroups: ['内容与增长组', '前端体验与 QA 组'],
    redfoxSkills: [
      '抖音热门相似账号',
      '小红书热门相似账号',
      '公众号热门相似账号',
      'B 站搜账号',
      'TikTok 账号搜索',
    ],
    workflow: [
      '投放目标配置',
      '达人搜索',
      '账号评分',
      'CRM/对标入库',
      '跟进任务生成',
    ],
    dataObjects: [
      'SolutionRun',
      'BenchmarkAccount',
      'CrmCustomer',
      'CrmTask',
      'GrowthLead',
    ],
    acceptance: ['生成候选池', '输出评分/风险/联系建议', '可创建跟进任务'],
    estimatedWorkdays: 7,
  },
  {
    code: 'viral-breakdown',
    name: '爆款拆解包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '输入链接或关键词后拆解爆款结构、评论反馈和复刻建议。',
    customerValue: '让创作团队快速复用被验证的内容结构。',
    entryPath: '/solutions/viral-breakdown',
    ownerGroups: ['内容与增长组', 'RedFox 接入组'],
    redfoxSkills: ['评论分析', '作品查询', 'B 站作品集', '公众号热门文章'],
    workflow: [
      '链接/关键词输入',
      '详情和评论采集',
      '爆款结构拆解',
      '创作建议生成',
    ],
    dataObjects: [
      'SolutionRun',
      'IntelligenceItem',
      'CommentInsight',
      'Material',
      'Topic',
    ],
    acceptance: [
      '输入链接后输出结构拆解',
      '输出复刻建议',
      '关联素材进入素材库',
    ],
    estimatedWorkdays: 6,
  },
  {
    code: 'private-asset-extractor',
    name: '私域素材提取包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '从文件、链接、短视频和搜索结果中提取可复用素材与知识。',
    customerValue: '把一线素材和私域沉淀转成知识库、素材库和内容生产输入。',
    entryPath: '/solutions/private-asset-extractor',
    ownerGroups: ['RedFox 接入组', '数据与工作流组'],
    redfoxSkills: [
      'PDF/图片文字提取',
      '短视频下载',
      '作品爬取',
      'Deepseek/豆包 WebSearch',
    ],
    workflow: ['文件/链接输入', '内容提取', '素材清洗', '知识库/素材库入库'],
    dataObjects: [
      'SolutionRun',
      'Material',
      'KnowledgeItem',
      'EvidenceAttachment',
    ],
    acceptance: ['文件或链接转素材记录', '保留来源和授权状态', '可同步知识库'],
    estimatedWorkdays: 6,
  },
  {
    code: 'aigc-asset-factory',
    name: 'AIGC 素材工厂',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '根据选题、文章、爆款样本生成封面、图片、视频提示词和素材包。',
    customerValue: '把情报和内容简报直接转成多格式素材，缩短生产周期。',
    entryPath: '/solutions/aigc-asset-factory',
    ownerGroups: ['RedFox 接入组', '前端体验与 QA 组'],
    redfoxSkills: [
      'GPT-image2',
      'seedream',
      'Seedance',
      '视频提示词',
      '小红书/公众号封面',
    ],
    workflow: [
      '选题/文章输入',
      '图片/封面/video prompt 生成',
      '素材生成',
      '素材库入库',
    ],
    dataObjects: [
      'SolutionRun',
      'Material',
      'RuntimeExecution',
      'RedfoxCallLog',
      'SolutionRunItem',
    ],
    acceptance: [
      '生成封面或视频 prompt/素材',
      '记录 prompt/模型/成本',
      '结果进入素材库',
    ],
    estimatedWorkdays: 8,
  },
  {
    code: 'multi-platform-copy',
    name: '多平台文案适配包',
    category: 'redfox_pool',
    implementationState: 'planned',
    summary: '把一份原文改写成小红书、公众号、知乎、抖音口播等平台版本。',
    customerValue: '减少重复改稿，让发布团队保持平台语气和规则一致。',
    entryPath: '/solutions/multi-platform-copy',
    ownerGroups: ['内容与增长组', '风控合规组'],
    redfoxSkills: [
      '多平台风格改写',
      '小红书改写',
      '公众号改写',
      '知乎改写',
      '标题生成评分',
    ],
    workflow: [
      '原文输入',
      '平台选择',
      '标题评分/改写',
      '多版本生成',
      '合规检查',
    ],
    dataObjects: ['SolutionRun', 'Article', 'ComplianceCheck', 'PublishRecord'],
    acceptance: [
      '生成小红书/公众号/知乎/抖音口播版本',
      '进入发布前检查',
      '保留改写依据',
    ],
    estimatedWorkdays: 6,
  },
  {
    code: 'account-diagnosis',
    name: '账号体检包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '围绕账号定位、内容节奏、互动质量、风险项和 30 天计划做诊断。',
    customerValue: '让运营知道账号为什么不涨，以及下一步应该修哪一环。',
    entryPath: '/solutions/account-diagnosis',
    ownerGroups: ['内容与增长组', '数据与工作流组'],
    redfoxSkills: [
      '抖音账号诊断',
      '小红书账号诊断',
      '公众号账号诊断',
      '抖音/公众号订阅追踪',
    ],
    workflow: ['账号输入', '诊断采集', '健康评分', '30 天计划生成', '自动跟踪'],
    dataObjects: [
      'SolutionRun',
      'GrowthAccountHealth',
      'BenchmarkAccount',
      'GrowthReport',
      'IntelligenceMonitor',
    ],
    acceptance: ['输出健康评分', '输出建议和风险项', '生成 30 天改进计划'],
    estimatedWorkdays: 7,
  },
  {
    code: 'brand-monitoring',
    name: '舆情/品牌词监控包',
    category: 'redfox_pool',
    implementationState: 'partial',
    summary: '监控品牌词、竞品词、负面舆情、热点关联和可回应机会。',
    customerValue: '让市场、客服和风控及时发现风险与机会，形成响应闭环。',
    entryPath: '/solutions/brand-monitoring',
    ownerGroups: ['风控合规组', '数据与工作流组'],
    redfoxSkills: [
      '全网热搜',
      'Deepseek/豆包 WebSearch',
      '平台搜索',
      '评论分析',
    ],
    workflow: ['品牌/竞品词配置', '搜索评论采集', '风险识别', '确认和日报生成'],
    dataObjects: [
      'SolutionRun',
      'IntelligenceMonitor',
      'IntelligenceItem',
      'ComplianceCheck',
      'AgentConfirmation',
    ],
    acceptance: [
      '监控品牌/负面/竞品词',
      '风险样本进入审核',
      '生成每日监控报告',
    ],
    estimatedWorkdays: 7,
  },
];
