import { type SidebarItem } from "@/components/application/sidebars/Sidebar Responsive/ts/sidebar";
import {
    Box,
    Bug,
    CalendarClock,
    ClipboardList,
    FileCheck2,
    FileText,
    Home,
    IdCard,
    Images,
    Inbox,
    Lightbulb,
    MessageCircle,
    MessagesSquare,
    MonitorCog,
    PenLine,
    Settings,
    ShieldCheck,
    SlidersHorizontal,
    Sparkles,
    SquareCheck,
    Target,
    UsersRound,
    Video,
} from "lucide-react";

export const sectionItems: SidebarItem[] = [
    {
        key: "workspace",
        title: "工作台",
        items: [
            {
                key: "/",
                href: "/",
                icon: Home,
                title: "总览",
            },
            {
                key: "/confirmations",
                href: "/confirmations",
                icon: SquareCheck,
                title: "待我确认",
            },
            {
                key: "/agent-console",
                href: "/agent-console",
                icon: Sparkles,
                title: "智能任务",
            },
            {
                key: "/execution-records",
                href: "/execution-records",
                icon: ClipboardList,
                title: "任务记录",
            },
            {
                key: "/artifacts",
                href: "/artifacts",
                icon: FileCheck2,
                title: "操作证据",
            },
        ],
    },
    {
        key: "content-production",
        title: "内容生产",
        items: [
            {
                key: "/materials",
                href: "/materials",
                icon: Box,
                title: "内容素材",
            },
            {
                key: "/topics",
                href: "/topics",
                icon: Lightbulb,
                title: "选题库",
            },
            {
                key: "/articles",
                href: "/articles",
                icon: FileText,
                title: "文章库",
            },
            {
                key: "/xiaohongshu",
                href: "/xiaohongshu",
                icon: MessageCircle,
                title: "小红书笔记",
            },
            {
                key: "/video-workshop",
                href: "/video-workshop",
                icon: Video,
                title: "视频工坊",
            },
            {
                key: "/strategies",
                href: "/strategies",
                icon: Target,
                title: "内容规则",
            },
        ],
    },
    {
        key: "publishing",
        title: "发布中心",
        items: [
            {
                key: "/distribution?tab=article",
                href: "/distribution?tab=article",
                icon: PenLine,
                title: "图文发布",
            },
            {
                key: "/distribution?tab=video",
                href: "/distribution?tab=video",
                icon: Video,
                title: "视频发布",
            },
            {
                key: "/distribution?tab=materials",
                href: "/distribution?tab=materials",
                icon: Images,
                title: "发布素材",
            },
            {
                key: "/distribution?tab=accounts",
                href: "/distribution?tab=accounts",
                icon: UsersRound,
                title: "平台账号",
            },
            {
                key: "/schedules",
                href: "/schedules",
                icon: CalendarClock,
                title: "计划任务",
            },
        ],
    },
    {
        key: "customer-interaction",
        title: "客户互动",
        items: [
            {
                key: "/workbench",
                href: "/workbench",
                icon: MessagesSquare,
                title: "互动总览",
            },
            {
                key: "/workbench/douyin-comments",
                href: "/workbench/douyin-comments",
                icon: MessageCircle,
                title: "抖音评论",
            },
            {
                key: "/workbench/douyin-messages",
                href: "/workbench/douyin-messages",
                icon: Inbox,
                title: "抖音私信",
            },
            {
                key: "/workbench/channel-comments",
                href: "/workbench/channel-comments",
                icon: MessageCircle,
                title: "视频号评论",
            },
            {
                key: "/workbench/channel-messages",
                href: "/workbench/channel-messages",
                icon: Inbox,
                title: "视频号私信",
            },
            {
                key: "/interaction/rules",
                href: "/interaction/rules",
                icon: SlidersHorizontal,
                title: "回复规则",
            },
            {
                key: "/interaction/records",
                href: "/interaction/records",
                icon: ClipboardList,
                title: "回复记录",
            },
        ],
    },
    {
        key: "system",
        title: "系统设置",
        items: [
            {
                key: "/local-engine",
                href: "/local-engine",
                icon: MonitorCog,
                title: "运行检查",
            },
            {
                key: "/capabilities/account",
                href: "/capabilities/account",
                icon: IdCard,
                title: "账号与设备",
            },
            {
                key: "/platforms",
                href: "/platforms",
                icon: UsersRound,
                title: "平台账号",
            },
            {
                key: "/settings",
                href: "/settings",
                icon: Settings,
                title: "系统配置",
            },
            {
                key: "/capabilities/risk",
                href: "/capabilities/risk",
                icon: ShieldCheck,
                title: "权限与安全",
            },
            {
                key: "/capabilities/users",
                href: "/capabilities/users",
                icon: UsersRound,
                title: "用户与角色",
            },
            {
                key: "/distribution?tab=logs",
                href: "/distribution?tab=logs",
                icon: Bug,
                title: "诊断日志",
            },
        ],
    },
];
