export function commercialDisplayText(value: unknown, fallback = "") {
  const text =
    typeof value === "string"
      ? value
      : value == null
        ? fallback
        : String(value);
  if (!text) return fallback;

  return text
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\bcommercial-e2e-[\w.-]+/gi, "素材")
    .replace(/\bcommercial-acceptance-[\w.-]+/gi, "素材")
    .replace(/\bcommercial-publishing-center-confirmation\b/gi, "发布中心确认任务")
    .replace(/\bcommercial-pressure-\d+\b/gi, "发布检查")
    .replace(/\bcommercial-[\w.-]+/gi, "业务任务")
    .replace(/\b(?:smoke|test|fixture|internal)[-_][\w.-]+/gi, "素材")
    .replace(/\baccount\/executor\s+preflight\b/gi, "账号执行前检查")
    .replace(/\btarget-read\s+capability\b/gi, "目标读取能力")
    .replace(/\breply-generate\s+capability\b/gi, "回复生成能力")
    .replace(/\bcontrolled-send\s+capability\b/gi, "受控发送能力")
    .replace(/\bexecutor\s+preflight\b/gi, "执行前检查")
    .replace(/\bcapability\b/gi, "能力")
    .replace(/\bpreflight\b/gi, "检查")
    .replace(
      /https?:\/\/(?:localhost|127\.0\.0\.1):\d+\/api\/[^\s·；，。)）]*/gi,
      "本机业务服务",
    )
    .replace(/internal:\/\/[^\s·；，。)）]*/gi, "本机服务")
    .replace(/https?:\/\/example\.com\/[^\s·；，。)）]*/gi, "业务来源页面")
    .replace(/https?:\/\/(?:localhost|127\.0\.0\.1):\d+[^\s·；，。)）]*/gi, "本机服务地址")
    .replace(/(?:\/Users|\/Volumes|\/private|\/tmp|\/var)\/[^\s·；，。)）]*/g, "本机文件")
    .replace(/[A-Za-z]:\\[^\s·；，。)）]*/g, "本机文件")
    .replace(/[（(]\s*(?:模型|model)\s*[：:]\s*[\w.-]+\s*[)）]/gi, "")
    .replace(
      /\b(?:pid|profile|stage|windowStatus|dbStatus|helperStatus|cookiesFile|path)\s*=\s*[^\s,，；]+/gi,
      "",
    )
    .replace(/\/api\/[^\s·；，。)）]*/gi, "业务服务")
    .replace(/\bagent[-_ ]?s\b/gi, "本机助手")
    .replace(/\bsidecar(?:\s+engine)?\b/gi, "独立服务")
    .replace(/\brunner\b|\brunners\b/gi, "执行流程")
    .replace(/\bnode-agent-runtime\b/gi, "本机任务服务")
    .replace(/Python\s+独立服务/gi, "外部辅助服务")
    .replace(/Python\s+sidecar/gi, "外部辅助服务")
    .replace(/3011\s*本地\s*Runtime/gi, "本机执行服务")
    .replace(/17777\s*Python\s*sidecar/gi, "外部辅助服务")
    .replace(/\bbrowser-control\b/gi, "浏览器操作能力")
    .replace(/\bPlaywright\b/gi, "浏览器操作能力")
    .replace(/\bChrome\s+for\s+Testing\b/gi, "本机浏览器")
    .replace(/RedFox\s*官方\s*/gi, "官方")
    .replace(/RedFox/gi, "外部数据")
    .replace(/\bSkillHub\b/gi, "能力服务")
    .replace(/\bSkills\b/gi, "能力")
    .replace(/\bSkill\b/gi, "能力")
    .replace(/技能编排|插件与技能|插件目录|插件/g, "扩展能力")
    .replace(/API/g, "数据能力")
    .replace(/\bapi\b|endpoint/gi, "数据能力")
    .replace(/\bbackend\b/gi, "业务服务")
    .replace(/\bMCP\b/gi, "自动化服务")
    .replace(/接口/g, "服务")
    .replace(/后端/g, "业务服务")
    .replace(/工作流/g, "流程")
    .replace(/执行记录/g, "任务结果")
    .replace(/操作记录/g, "结果留存")
    .replace(/计划任务/g, "定时任务")
    .replace(/任务运行/g, "任务进度")
    .replace(/发布流程/g, "发布准备")
    .replace(/接入状态/g, "落地进度")
    .replace(/当前状态/g, "当前进度")
    .replace(/合规负责人/g, "复核负责人")
    .replace(/合规审核|合规复核|合规审阅/g, "风险复核")
    .replace(/需合规/g, "需复核")
    .replace(/先合规/g, "先复核")
    .replace(/合规/g, "风险复核")
    .replace(/工程风险/g, "发布风险")
    .replace(/工程/g, "产品")
    .replace(/前业务服务/g, "应用")
    .replace(/前后端/g, "应用")
    .replace(/\bexecutor\b|\bexecutors\b/gi, "处理能力")
    .replace(/执行器/g, "处理能力")
    .replace(/\bRuntimeOrchestrator\b/gi, "运行调度")
    .replace(/runtime billing reserve failed/gi, "云端积分冻结未完成")
    .replace(/真实执行需要先完成云端积分冻结，本次动作已拦截。/g, "需要先完成云端授权和积分冻结，系统已停止本次外发动作。")
    .replace(/真实执行扣积分需要当前账号接通 (?:Kaypal|JIUZHANG AI) 云端授权，请在「账号与设备」重新登录后再执行。/g, "需要当前账号完成 JIUZHANG AI 云端授权，请到账号与设备重新登录后再执行。")
    .replace(/后端风控审批已记录/g, "风控确认已记录")
    .replace(/后端风控审计/g, "风控确认记录")
    .replace(/账号、设备、动作、风险等级和确认记录已写入审计事件。/g, "账号、设备、动作、风险等级和确认结果已留存。")
    .replace(/diagnostic_bundle/gi, "排查资料")
    .replace(/stage_log/gi, "步骤记录")
    .replace(/failure_reason/gi, "失败原因")
    .replace(/阶段日志：环境检查开始。/g, "环境检查开始。")
    .replace(/本地引擎已领取任务，开始检查执行环境。/g, "本机服务已开始检查执行环境。")
    .replace(/浏览器控制、桌面控制和文件访问状态开始检查。/g, "正在检查浏览器、桌面和文件访问状态。")
    .replace(/商用执行权限：允许/g, "执行权限：允许")
    .replace(/阶段日志已开启：任务创建/g, "步骤记录已开启：任务创建")
    .replace(/需要登录，本次不会伪造成已执行。/g, "需要登录，本次不会模拟执行结果。")
    .replace(/需要登录，任务已阻断。/g, "需要登录，任务需处理。")
    .replace(/证据链不完整：缺少浏览器证据索引/g, "执行记录不完整：缺少页面操作记录")
    .replace(/已识别真实抖音自动评论对象，等待继续执行。/g, "已识别目标评论，等待继续执行。")
    .replace(/已识别真实抖音私信回复对象，等待继续执行。/g, "已识别目标私信，等待继续执行。")
    .replace(/抖音目标评论不存在或已被删除/g, "目标评论不存在或已被删除")
    .replace(/抖音目标私信不存在或已过期/g, "目标私信不存在或已过期")
    .replace(/商业验收真实测试对象/g, "验收测试对象")
    .replace(/\bruntime billing reserve failed\b/gi, "云端授权和积分冻结未完成")
    .replace(/native\s+runtime/gi, "本机服务")
    .replace(/\bNative\b/gi, "本机")
    .replace(/\bRuntime\b|\bruntime\b/gi, "本机服务")
    .replace(/\bHelper\b|\bhelper\b/g, "辅助服务")
    .replace(/PowerShell/gi, "旧版脚本")
    .replace(/\bWindows\s+VM\b/gi, "Windows 测试环境")
    .replace(/\bVM\b/g, "测试环境")
    .replace(/USB\s+token/gi, "签名设备")
    .replace(/\bnative\s+DLL\b/gi, "本机能力")
    .replace(/\bruntime[-_\s]*executions?(?:\.(?:log|记录))?\b/gi, "执行结果记录")
    .replace(/\bexecutions?(?:\.(?:log|记录))?\b/gi, "执行结果记录")
    .replace(/\bbundle\b/gi, "安装包")
    .replace(/\bPostInstall\b/gi, "安装后处理")
    .replace(/\bpost-install\b/gi, "安装后处理")
    .replace(/\bbootstrap\b/gi, "安装窗口")
    .replace(/\bNSIS\b/g, "安装程序")
    .replace(/\bJSON\b/g, "数据结果")
    .replace(/\bANSI\b|\bUTF-8\b/gi, "文字编码")
    .replace(/\bOSS\b/g, "云端更新源")
    .replace(/\bopenim\b/gi, "非好友对象")
    .replace(/\bUIA\b/gi, "桌面识别")
    .replace(/\bOCR\b/gi, "文字识别")
    .replace(/UIA\/文字识别/gi, "桌面识别")
    .replace(/桌面识别\/文字识别/gi, "桌面识别")
    .replace(/DB\/RPA/gi, "本机能力")
    .replace(/DB\/辅助服务/gi, "本机数据读取")
    .replace(/数据通道\/辅助服务/gi, "本机数据读取")
    .replace(/\bDB\b/g, "数据通道")
    .replace(/contact\.db/gi, "本机联系人库")
    .replace(/SQLite/gi, "本机数据")
    .replace(/\bsqlite\b/gi, "本机数据")
    .replace(/Postgres|postgres/gi, "云端数据")
    .replace(/\breadiness\b/gi, "状态检查")
    .replace(/controlled-检查/gi, "检查")
    .replace(/\bdry-run\b|\bdry run\b/gi, "检查")
    .replace(/\bnot_integrated\b/gi, "暂未开通")
    .replace(/detected-not-runnable/gi, "当前不可执行")
    .replace(/unsupported_platform/gi, "平台暂不支持")
    .replace(/\bblocked\b/gi, "需处理")
    .replace(/\bready\b/gi, "可使用")
    .replace(/\bmissing\b/gi, "缺少配置")
    .replace(/\bfallback\b/gi, "备用方案")
    .replace(/\bmock\b/gi, "模拟环境")
    .replace(/\bdemo\b/gi, "演示环境")
    .replace(/\bpayloads?\b/gi, "提交内容")
    .replace(/\bschema\b/gi, "字段规则")
    .replace(/\bcontract\b/gi, "连接方案")
    .replace(/\bProof\b|\bproof\b/g, "凭证")
    .replace(/\bConnector\b|\bconnector\b/g, "连接")
    .replace(/\bLease\b|\blease\b/g, "任务锁")
    .replace(/\bcron\b/gi, "定时任务")
    .replace(/\bdaemon\b/gi, "后台任务")
    .replace(/\bsession\b|\bsessions\b/gi, "任务记录")
    .replace(/\bartifact\b|\bartifacts\b/gi, "操作结果")
    .replace(/\bsnapshot\b/gi, "页面记录")
    .replace(/\bscreen\b/gi, "屏幕")
    .replace(/\blog\b|\blogs\b/gi, "记录")
    .replace(/\bdiagnostics?\b/gi, "排查信息")
    .replace(/\bdebug\b/gi, "排查")
    .replace(/writeTables|no-token|no-write|no-network/gi, "安全限制")
    .replace(/OAuth/gi, "授权")
    .replace(/\btoken\b|Token/g, "授权凭证")
    .replace(/密钥/g, "授权信息")
    .replace(/Webhook|webhook/g, "企业微信连接地址")
    .replace(/租户/g, "组织")
    .replace(/\btenantId\b|\bactorUserId\b/gi, "组织与操作者")
    .replace(/\btenant\b/gi, "组织")
    .replace(/\bentitlement\b/gi, "权益")
    .replace(/点数上限|使用上限|预算点数/g, "用量")
    .replace(/扣费/g, "扣积分")
    .replace(/试运行/g, "生成")
    .replace(/试跑/g, "生成")
    .replace(/本地引擎/g, "本机服务")
    .replace(/本机引擎/g, "本机服务")
    .replace(/运行时/g, "本机服务")
    .replace(/运行日志/g, "运行记录")
    .replace(/系统日志/g, "系统记录")
    .replace(/诊断日志/g, "高级信息")
    .replace(/诊断包/g, "排查资料")
    .replace(/失败诊断/g, "失败原因")
    .replace(/执行诊断/g, "执行详情")
    .replace(/导出诊断/g, "导出排查资料")
    .replace(/阻断项/g, "需处理项")
    .replace(/阻断\/未真实化/g, "需处理")
    .replace(/未真实化/g, "未接通")
    .replace(/真实化检查/g, "状态检查")
    .replace(/有阻断/g, "需处理")
    .replace(/已阻断/g, "需处理")
    .replace(/阻断/g, "需处理")
    .replace(/预检合规/g, "发布检查")
    .replace(/发布日志/g, "发布记录")
    .replace(/发布队列/g, "发布任务")
    .replace(/发现队列/g, "待处理线索")
    .replace(/渠道队列/g, "渠道任务")
    .replace(/产物与证据/g, "结果留存")
    .replace(/证据回读/g, "结果")
    .replace(/证据回流/g, "结果回传")
    .replace(/证据指纹/g, "记录校验码")
    .replace(/证据编号/g, "记录编号")
    .replace(/审计证据/g, "审计记录")
    .replace(/连接证据/g, "连接记录")
    .replace(/回滚证据/g, "回退记录")
    .replace(/预检证据/g, "检查记录")
    .replace(/Agent\s*过程证据/gi, "任务过程记录")
    .replace(/Agent\s*会话/gi, "任务记录")
    .replace(/Agent\s*过程记录/gi, "任务过程记录")
    .replace(/任务会话/g, "任务记录")
    .replace(/会话记录/g, "任务记录")
    .replace(/会话/g, "任务")
    .replace(/Payload\s*摘要/gi, "提交内容摘要")
    .replace(/Payload/gi, "提交内容")
    .replace(/Preflight\s*检查/gi, "发布前检查")
    .replace(/Dry Run/gi, "预发布检查")
    .replace(/字段映射/g, "字段匹配")
    .replace(/审计编号/g, "记录编号")
    .replace(/来源日志/g, "来源记录")
    .replace(/对象 ID/g, "对象编号")
    .replace(/确认 ID/g, "确认编号")
    .replace(/写入表/g, "写入范围")
    .replace(/外部授权/g, "第三方授权")
    .replace(/外部 CRM/g, "第三方 CRM")
    .replace(/外部连接/g, "第三方连接")
    .replace(/合同/g, "方案")
    .replace(/数据通道\s*辅助服务/g, "本机数据读取")
    .replace(/模型配置/g, "AI 能力设置")
    .replace(/大语言模型/g, "AI 模型")
    .replace(/文件路径/g, "文件位置")
    .replace(/端口\s*\d+/g, "服务通道")
    .replace(/PID[:：]?\s*[\w-]+/g, "进程已记录")
    .replace(/\bwxid_[\w-]+/gi, "旧微信账号")
    .replace(/\byanghylive_[\w-]+/gi, "当前微信账号")
    .replace(/\bwindows-wechat-db-decrypted\b/gi, "本机联系人读取成功")
    .replace(/\brelease:verify\b/gi, "发布校验")
    .replace(/\bblockmap\b/gi, "更新校验文件")
    .replace(/KaypalAI\.exe/g, "旧主程序")
    .replace(/KaypalAI内容创作平台\.exe/g, "主程序")
    .replace(/package\.json/g, "打包配置")
    .replace(/electron-builder\s+extraResources/gi, "安装包资源")
    .replace(/app-update\.yml/g, "更新配置")
    .replace(/here-string/gi, "脚本写法")
    .replace(/osascript\/System Events/gi, "系统辅助访问")
    .replace(/ForEach-Object\s*:\s*Cannot convert value "[^"]+" to type System\.Int32/gi, "本机脚本处理失败")
    .replace(/billing\/AI proxy key/gi, "AI 服务授权")
    .replace(/sourcePath/g, "来源位置")
    .replace(/helperError|keyHelperStatus|decryptionStatus|resultSource/g, "排查字段")
    .replace(/\bkey\b/gi, "授权信息")
    .replace(/\s+/g, " ")
    .trim();
}

export function commercialDisplayList(values: string[] | null | undefined) {
  return (values || [])
    .map((value) => commercialDisplayText(value))
    .filter(Boolean);
}

/**
 * Copy shown above the fold must stay task-oriented. Keep implementation
 * details available to the caller for an advanced disclosure instead.
 */
export function commercialPrimaryText(value: unknown, fallback = "") {
  const text = commercialDisplayText(value, fallback);
  if (!text) return fallback;

  return text
    .replace(/(?:预检|验收|证据链|底座|回读|执行器|JSON|smoke)/gi, "")
    .replace(/\b(?:pipeline|orchestrator|runtime|schema|payload)\b/gi, "")
    .replace(/\s{2,}/g, " ")
    .replace(/\s*([，。；：])/g, "$1")
    .replace(/[，、；：]\s*$/g, "")
    .trim() || fallback;
}
